"use client";

import { useState } from "react";
import type { DatabaseColumn } from "@/types";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { X } from "lucide-react";

interface ColumnEditorProps {
  initialColumn?: DatabaseColumn | null;
  onSave: (column: DatabaseColumn) => void;
  onCancel: () => void;
}

const COMMON_DATA_TYPES = [
  "UUID",
  "VARCHAR(255)",
  "VARCHAR(100)",
  "VARCHAR(50)",
  "TEXT",
  "INTEGER",
  "BIGINT",
  "DECIMAL(10,2)",
  "DECIMAL(12,2)",
  "BOOLEAN",
  "TIMESTAMP",
  "DATE",
  "JSONB",
];

export function ColumnEditor({ initialColumn, onSave, onCancel }: ColumnEditorProps) {
  const isEdit = Boolean(initialColumn?.id);
  const [column, setColumn] = useState<DatabaseColumn>(() => {
    if (initialColumn) return { ...initialColumn };
    return {
      id: crypto.randomUUID(),
      name: "",
      type: "VARCHAR(255)",
      nullable: true,
      isPrimaryKey: false,
      isUnique: false,
      defaultValue: "",
      autoGenerated: false,
      description: "",
    };
  });

  const [isCustomType, setIsCustomType] = useState(() => {
    return initialColumn ? !COMMON_DATA_TYPES.includes(initialColumn.type) : false;
  });

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!column.name.trim()) return;
    onSave({
      ...column,
      name: column.name.trim().toLowerCase(),
      type: column.type.trim(),
    });
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4 backdrop-blur-sm animate-in fade-in duration-200">
      <Card className="w-full max-w-lg overflow-hidden border-border bg-card shadow-2xl">
        <CardHeader className="flex flex-row items-center justify-between border-b border-border/50 pb-4">
          <CardTitle className="text-lg">{isEdit ? "Edit Column" : "Add New Column"}</CardTitle>
          <Button variant="ghost" size="icon" className="h-8 w-8" onClick={onCancel}>
            <X className="h-4 w-4" />
          </Button>
        </CardHeader>
        <form onSubmit={handleSubmit}>
          <CardContent className="space-y-4 pt-4">
            <div className="grid gap-3 sm:grid-cols-2">
              <label className="grid gap-1.5 text-xs font-medium">
                <span>Column Name <span className="text-red-400">*</span></span>
                <input
                  type="text"
                  required
                  placeholder="e.g. customer_id"
                  className="rounded-md border border-border bg-secondary/40 px-3 py-2 text-sm font-mono focus:border-primary focus:outline-none"
                  value={column.name}
                  onChange={(e) => setColumn({ ...column, name: e.target.value })}
                />
              </label>

              <label className="grid gap-1.5 text-xs font-medium">
                <span>Data Type</span>
                {isCustomType ? (
                  <div className="flex gap-1">
                    <input
                      type="text"
                      required
                      placeholder="e.g. GEOMETRY"
                      className="w-full rounded-md border border-border bg-secondary/40 px-3 py-2 text-sm font-mono focus:border-primary focus:outline-none"
                      value={column.type}
                      onChange={(e) => setColumn({ ...column, type: e.target.value })}
                    />
                    <Button
                      type="button"
                      variant="ghost"
                      size="sm"
                      className="text-[10px]"
                      onClick={() => {
                        setIsCustomType(false);
                        setColumn({ ...column, type: COMMON_DATA_TYPES[0] });
                      }}
                    >
                      List
                    </Button>
                  </div>
                ) : (
                  <select
                    className="rounded-md border border-border bg-secondary/40 px-3 py-2 text-sm font-mono focus:border-primary focus:outline-none"
                    value={column.type}
                    onChange={(e) => {
                      if (e.target.value === "CUSTOM") {
                        setIsCustomType(true);
                        setColumn({ ...column, type: "" });
                      } else {
                        setColumn({ ...column, type: e.target.value });
                      }
                    }}
                  >
                    {COMMON_DATA_TYPES.map((t) => (
                      <option key={t} value={t}>
                        {t}
                      </option>
                    ))}
                    <option value="CUSTOM">+ Custom Type...</option>
                  </select>
                )}
              </label>
            </div>

            <div className="grid grid-cols-2 gap-3 rounded-lg border border-border/50 bg-secondary/20 p-3">
              <label className="flex items-center gap-2 text-xs font-medium cursor-pointer">
                <input
                  type="checkbox"
                  className="rounded border-border bg-secondary"
                  checked={column.isPrimaryKey}
                  onChange={(e) => {
                    const checked = e.target.checked;
                    setColumn({
                      ...column,
                      isPrimaryKey: checked,
                      nullable: checked ? false : column.nullable,
                    });
                  }}
                />
                <span>Primary Key (PK)</span>
              </label>

              <label className="flex items-center gap-2 text-xs font-medium cursor-pointer">
                <input
                  type="checkbox"
                  className="rounded border-border bg-secondary"
                  checked={column.nullable}
                  disabled={column.isPrimaryKey}
                  onChange={(e) => setColumn({ ...column, nullable: e.target.checked })}
                />
                <span>Nullable</span>
              </label>

              <label className="flex items-center gap-2 text-xs font-medium cursor-pointer">
                <input
                  type="checkbox"
                  className="rounded border-border bg-secondary"
                  checked={column.isUnique}
                  onChange={(e) => setColumn({ ...column, isUnique: e.target.checked })}
                />
                <span>Unique</span>
              </label>

              <label className="flex items-center gap-2 text-xs font-medium cursor-pointer">
                <input
                  type="checkbox"
                  className="rounded border-border bg-secondary"
                  checked={column.autoGenerated}
                  onChange={(e) => setColumn({ ...column, autoGenerated: e.target.checked })}
                />
                <span>Auto Generated</span>
              </label>
            </div>

            <label className="grid gap-1.5 text-xs font-medium">
              <span>Default Value</span>
              <input
                type="text"
                placeholder="e.g. gen_random_uuid(), CURRENT_TIMESTAMP, 'ACTIVE'"
                className="rounded-md border border-border bg-secondary/40 px-3 py-2 text-sm font-mono focus:border-primary focus:outline-none"
                value={column.defaultValue ?? ""}
                onChange={(e) => setColumn({ ...column, defaultValue: e.target.value })}
              />
            </label>

            <label className="grid gap-1.5 text-xs font-medium">
              <span>Description / Column Notes</span>
              <textarea
                rows={2}
                placeholder="Purpose of this column in the schema..."
                className="rounded-md border border-border bg-secondary/40 p-2.5 text-xs focus:border-primary focus:outline-none"
                value={column.description}
                onChange={(e) => setColumn({ ...column, description: e.target.value })}
              />
            </label>

            <div className="flex justify-end gap-2 pt-2 border-t border-border/50">
              <Button type="button" variant="outline" size="sm" onClick={onCancel}>
                Cancel
              </Button>
              <Button type="submit" size="sm">
                Save Column
              </Button>
            </div>
          </CardContent>
        </form>
      </Card>
    </div>
  );
}
