/** Rich content for roadmap levels 18–22 */

export const LEVELS_18_22 = {
  "Authentication & JWT": {
    overview: "Authentication verifies identity; JWT (JSON Web Token) provides stateless, signed tokens containing claims. Spring Security integrates both for secure APIs.",
    whyItExists: "Microservices can't share server sessions. JWT enables stateless auth where any service validates tokens independently using shared public key.",
    internalWorking: "Login validates credentials, issues signed JWT (header.payload.signature). Each request sends Bearer token. Resource server validates signature and expiry. Refresh tokens enable long sessions.",
    realWorldUsage: "CommerceX user login returns access+refresh tokens. API gateway validates JWT. FinFlow MFA adds second factor. Token expiry: 15min access, 7d refresh.",
    codeExample: `@PostMapping("/login")\npublic TokenResponse login(@RequestBody LoginRequest req) {\n    Authentication auth = authManager.authenticate(\n        new UsernamePasswordAuthenticationToken(req.email(), req.password()));\n    String accessToken = jwtService.generateAccessToken(auth);\n    String refreshToken = jwtService.generateRefreshToken(auth);\n    return new TokenResponse(accessToken, refreshToken);\n}`,
    productionCode: `@Bean\npublic SecurityFilterChain filterChain(HttpSecurity http) throws Exception {\n    return http.csrf(AbstractHttpConfigurer::disable)\n        .sessionManagement(s -> s.sessionCreationPolicy(STATELESS))\n        .authorizeHttpRequests(auth -> auth\n            .requestMatchers("/api/v1/auth/**").permitAll()\n            .anyRequest().authenticated())\n        .addFilterBefore(jwtFilter, UsernamePasswordAuthenticationFilter.class)\n        .build();\n}`,
    bestPractices: ["Use short-lived access tokens", "Store refresh tokens securely (httpOnly cookie)", "Validate token signature and expiry", "Never store secrets in JWT payload"],
    commonMistakes: ["Storing sensitive data in JWT claims", "No token expiry", "Symmetric key in multiple services", "Not invalidating tokens on logout"],
    interviewQuestions: [
      { question: "JWT vs session-based auth?", answer: "Session: state on server, easy revocation, harder to scale. JWT: stateless, scales horizontally, harder to revoke. Use JWT for microservices with short expiry + refresh tokens." },
    ],
  },
  "OAuth2 & RBAC": {
    overview: "OAuth2 delegates authorization to identity providers. RBAC (Role-Based Access Control) assigns permissions via roles (ADMIN, USER, MERCHANT).",
    whyItExists: "Users shouldn't share passwords with third-party apps. OAuth2 enables 'Login with Google' securely. RBAC enforces least-privilege access in enterprise systems.",
    internalWorking: "Authorization Code flow: redirect to IdP, exchange code for token. Scopes limit access. RBAC: User→Roles→Permissions. @PreAuthorize checks roles at method level.",
    realWorldUsage: "FinFlow OAuth2 for partner API access. CommerceX merchant vs customer roles. @PreAuthorize('hasRole(ADMIN)') on admin endpoints. Keycloak as identity provider.",
    codeExample: `@PreAuthorize("hasRole('ADMIN') or #userId == authentication.principal.id")\n@GetMapping("/users/{userId}/orders")\npublic List<OrderDto> getUserOrders(@PathVariable Long userId) {\n    return orderService.findByUserId(userId);\n}`,
    productionCode: `spring:\n  security:\n    oauth2:\n      resourceserver:\n        jwt:\n          issuer-uri: https://auth.finflow.com/realms/production\n          jwk-set-uri: https://auth.finflow.com/realms/production/protocol/openid-connect/certs`,
    bestPractices: ["Use Authorization Code flow for web apps", "Implement least privilege", "Audit role assignments", "Separate authentication and authorization concerns"],
    commonMistakes: ["Implicit flow (deprecated)", "Overly broad scopes", "Hardcoded roles in code", "Missing method-level security"],
    interviewQuestions: [
      { question: "Explain OAuth2 Authorization Code flow.", answer: "Client redirects user to IdP login. IdP returns auth code to callback URL. Client exchanges code for access token (server-side). Most secure flow for web/mobile apps." },
    ],
  },
  "Docker & Containerization": {
    overview: "Docker packages applications with dependencies into portable containers. Dockerfile defines build steps; docker-compose orchestrates multi-container local environments.",
    whyItExists: "Works on my machine problems plague teams. Containers ensure identical environments from dev to prod. Immutable infrastructure enables reliable deployments.",
    internalWorking: "Dockerfile layers cached for fast rebuilds. Multi-stage builds separate build and runtime. Containers share host kernel, isolated via namespaces/cgroups.",
    realWorldUsage: "Each CommerceX microservice has a Dockerfile. docker-compose.yml runs full stack locally. Distroless/eclipse-temurin JRE images for minimal attack surface.",
    codeExample: `# Multi-stage Dockerfile\nFROM eclipse-temurin:21-jdk AS build\nWORKDIR /app\nCOPY . .\nRUN ./mvnw package -DskipTests\n\nFROM eclipse-temurin:21-jre\nCOPY --from=build /app/target/*.jar app.jar\nEXPOSE 8080\nENTRYPOINT ["java", "-jar", "app.jar"]`,
    productionCode: `# docker-compose.yml\nservices:\n  order-service:\n    build: ./order-service\n    ports: ["8084:8080"]\n    environment:\n      SPRING_PROFILES_ACTIVE: docker\n      KAFKA_BROKERS: kafka:9092\n    depends_on: [postgres, kafka, redis]`,
    bestPractices: ["Multi-stage builds for smaller images", "Run as non-root user", "Pin base image versions", "Use .dockerignore"],
    commonMistakes: ["Running as root in container", "Huge images (including JDK in prod)", "Storing secrets in Dockerfile", "Not using health checks"],
    interviewQuestions: [
      { question: "Docker vs VM?", answer: "VM: full OS per instance, GBs, minutes to start. Container: shares kernel, MBs, seconds to start. Containers lighter but less isolated than VMs. Use containers for microservices." },
    ],
  },
  "Kubernetes Orchestration": {
    overview: "Kubernetes orchestrates container deployment, scaling, and management. Pods, Services, Deployments, and Ingress manage application lifecycle in clusters.",
    whyItExists: "Managing hundreds of containers manually is impossible. K8s provides self-healing, auto-scaling, rolling updates, and service discovery for production workloads.",
    internalWorking: "Deployment manages ReplicaSets managing Pods. Service provides stable DNS/IP. Ingress routes external traffic. ConfigMap/Secret inject configuration. HPA auto-scales on metrics.",
    realWorldUsage: "CommerceX deployed on EKS with 3 replicas per service. Helm charts package K8s manifests. Liveness/readiness probes via Actuator. HPA scales on CPU/custom metrics.",
    codeExample: `apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: order-service\nspec:\n  replicas: 3\n  template:\n    spec:\n      containers:\n      - name: order-service\n        image: commercex/order-service:1.2.0\n        ports: [{containerPort: 8080}]\n        livenessProbe:\n          httpGet: {path: /actuator/health/liveness, port: 8080}`,
    productionCode: `# Helm values.yaml\nreplicaCount: 3\nresources:\n  requests: {cpu: 250m, memory: 512Mi}\n  limits: {cpu: 500m, memory: 1Gi}\nautoscaling:\n  enabled: true\n  minReplicas: 3\n  maxReplicas: 10\n  targetCPUUtilization: 70`,
    bestPractices: ["Set resource requests and limits", "Use liveness and readiness probes", "Deploy via Helm charts", "Implement PodDisruptionBudgets"],
    commonMistakes: ["No resource limits (noisy neighbor)", "Missing health probes", "Latest tag in production", "Running single replica in prod"],
    interviewQuestions: [
      { question: "Deployment vs StatefulSet?", answer: "Deployment: stateless, interchangeable pods, random names. StatefulSet: stable network identity, ordered deployment, persistent storage per pod. Use StatefulSet for databases, Kafka." },
    ],
  },
  "AWS Core Services": {
    overview: "AWS provides cloud infrastructure: EC2 (compute), RDS (managed DB), S3 (object storage), EKS (Kubernetes), SQS/SNS (messaging), and IAM (access control).",
    whyItExists: "Building and maintaining physical infrastructure is expensive and slow. AWS provides on-demand, scalable, pay-per-use infrastructure with global availability.",
    internalWorking: "VPC isolates network resources. IAM roles grant service permissions without keys. RDS handles backups, patching, failover. S3 stores objects with 99.999999999% durability.",
    realWorldUsage: "CommerceX on EKS with RDS PostgreSQL. Product images in S3. SQS for async processing. CloudFront CDN for static assets. IAM roles for service-to-service auth.",
    codeExample: `# Terraform RDS\nresource "aws_db_instance" "main" {\n  engine         = "postgres"\n  instance_class = "db.r6g.large"\n  allocated_storage = 100\n  multi_az       = true\n  backup_retention_period = 7\n}`,
    productionCode: `spring:\n  cloud:\n    aws:\n      s3:\n        bucket: commercex-assets\n      region:\n        static: us-east-1\n  datasource:\n    url: jdbc:postgresql://\${RDS_ENDPOINT}:5432/commercex`,
    bestPractices: ["Use IAM roles, not access keys", "Enable Multi-AZ for production RDS", "Tag all resources", "Use VPC private subnets for databases"],
    commonMistakes: ["Public RDS instances", "Hardcoded AWS credentials", "No backup strategy", "Over-provisioned instances"],
    interviewQuestions: [
      { question: "RDS vs self-managed PostgreSQL on EC2?", answer: "RDS: managed backups, patching, failover, monitoring. EC2: full control, lower cost at scale, you manage everything. Use RDS for most workloads; EC2 for special requirements." },
    ],
  },
  "Cloud-Native Architecture": {
    overview: "Cloud-native apps exploit cloud elasticity: microservices, containers, dynamic orchestration, and managed services. Designed for resilience, observability, and automation.",
    whyItExists: "Traditional architectures can't scale with demand spikes or survive infrastructure failures. Cloud-native patterns enable 99.99% availability and elastic cost optimization.",
    internalWorking: "12-Factor App principles guide design. Immutable infrastructure: replace, don't patch. Horizontal scaling via stateless services. Managed services reduce operational burden.",
    realWorldUsage: "CommerceX: stateless services on EKS, managed RDS/Kafka/ElastiCache. Auto-scaling for Black Friday traffic. Multi-AZ deployment. Infrastructure as Code with Terraform.",
    codeExample: `# Cloud-native checklist\n# ✓ Stateless services (state in Redis/DB)\n# ✓ Health endpoints (/actuator/health)\n# ✓ Config via environment variables\n# ✓ Graceful shutdown handling\n# ✓ Structured JSON logging\n# ✓ Distributed tracing (OpenTelemetry)`,
    productionCode: `@PreDestroy\npublic void shutdown() {\n    log.info("Shutting down gracefully...");\n    kafkaListenerContainer.stop();\n    taskExecutor.shutdown();\n    awaitTermination(taskExecutor, 30, SECONDS);\n}`,
    bestPractices: ["Design for failure (everything fails eventually)", "Implement graceful shutdown", "Use managed services over self-hosted", "Automate everything (IaC, CI/CD)"],
    commonMistakes: ["Lift-and-shift without refactoring", "Stateful services preventing scaling", "No disaster recovery plan", "Treating cloud like on-prem datacenter"],
    interviewQuestions: [
      { question: "What are the 12-Factor App principles?", answer: "Key ones: config in environment, treat backing services as attached resources, stateless processes, port binding, disposability (fast startup/shutdown), logs as event streams, admin as one-off processes." },
    ],
  },
  "CI/CD Pipelines": {
    overview: "CI/CD automates build, test, and deployment. Continuous Integration merges code frequently with automated tests. Continuous Delivery deploys to production reliably.",
    whyItExists: "Manual deployments are error-prone and slow. CI/CD enables teams to ship multiple times daily with confidence through automated quality gates.",
    internalWorking: "Pipeline stages: checkout→build→unit test→integration test→security scan→deploy staging→smoke test→deploy prod. GitHub Actions/Jenkins/GitLab CI orchestrate stages.",
    realWorldUsage: "Platform Engineering project provides reusable GitHub Actions templates. Every PR triggers build+test. Merge to main deploys to staging. Tag release deploys to production.",
    codeExample: `# .github/workflows/ci.yml\nname: CI\non: [push, pull_request]\njobs:\n  build:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/setup-java@v4\n        with: {java-version: '21', distribution: 'temurin'}\n      - run: ./mvnw verify\n      - run: docker build -t app:\${{ github.sha }} .`,
    productionCode: `  deploy:\n    needs: build\n    if: github.ref == 'refs/heads/main'\n    steps:\n      - run: helm upgrade --install order-service ./charts/order-service\n          --set image.tag=\${{ github.sha }}\n          --namespace production`,
    bestPractices: ["Fast feedback: unit tests under 5 minutes", "Build once, deploy everywhere (same artifact)", "Automated rollback capability", "Environment parity (dev≈staging≈prod)"],
    commonMistakes: ["No automated tests in pipeline", "Manual approval bottlenecks", "Different artifacts per environment", "Skipping staging deployment"],
    interviewQuestions: [
      { question: "CI vs CD difference?", answer: "CI: automatically build and test on every commit. CD (Continuous Delivery): always deployable, manual prod trigger. CD (Continuous Deployment): automatic prod deployment after tests pass." },
    ],
  },
  "GitOps & IaC": {
    overview: "GitOps uses Git as the single source of truth for infrastructure and deployment. IaC (Terraform/Pulumi) defines cloud resources in version-controlled code.",
    whyItExists: "Manual infrastructure changes cause drift and outages. GitOps provides audit trail, rollback via git revert, and automated reconciliation by operators like ArgoCD.",
    internalWorking: "Terraform plan/apply creates AWS resources from HCL files. ArgoCD watches Git repo, syncs K8s manifests to cluster. PR review process for all infrastructure changes.",
    realWorldUsage: "Platform Engineering: Terraform modules for VPC, EKS, RDS. ArgoCD deploys Helm charts from Git. Environment promotion via branch strategy (dev→staging→prod).",
    codeExample: `# Terraform EKS cluster\nmodule "eks" {\n  source  = "terraform-aws-modules/eks/aws"\n  cluster_name    = "commercex-prod"\n  cluster_version = "1.29"\n  vpc_id     = module.vpc.vpc_id\n  subnet_ids = module.vpc.private_subnets\n}`,
    productionCode: `# ArgoCD Application\napiVersion: argoproj.io/v1alpha1\nkind: Application\nmetadata:\n  name: order-service\nspec:\n  source:\n    repoURL: https://github.com/org/commercex-k8s\n    path: charts/order-service\n    targetRevision: main\n  destination:\n    server: https://kubernetes.default.svc\n    namespace: production`,
    bestPractices: ["All infra changes via PR", "Use Terraform modules for reusability", "Separate state files per environment", "Drift detection with scheduled plans"],
    commonMistakes: ["Manual kubectl apply in production", "Terraform state not in remote backend", "No PR review for infra changes", "Secrets in Terraform files"],
    interviewQuestions: [
      { question: "GitOps vs traditional CI/CD deployment?", answer: "Traditional: CI pipeline pushes to cluster. GitOps: cluster pulls from Git (reconciliation loop). GitOps provides continuous reconciliation, easier rollback (git revert), and drift detection." },
    ],
  },
  "Testing Strategy": {
    overview: "Testing pyramid: many unit tests, fewer integration tests, minimal E2E tests. Tools: JUnit 5, Mockito, TestContainers, RestAssured. TDD writes tests before code.",
    whyItExists: "Untested code breaks in production. Testing pyramid balances coverage with speed. Unit tests run in milliseconds; E2E tests catch integration issues.",
    internalWorking: "Unit: mock dependencies, test single class. Integration: @SpringBootTest with TestContainers for real DB/Kafka. Contract: verify API agreements between services. E2E: full user journey.",
    realWorldUsage: "80% unit (Mockito), 15% integration (TestContainers), 5% E2E. Pact for consumer-driven contracts. Mutation testing with PIT for critical payment logic.",
    codeExample: `@ExtendWith(MockitoExtension.class)\nclass OrderServiceTest {\n    @Mock OrderRepository repo;\n    @InjectMocks OrderService service;\n    @Test\n    void shouldCreateOrder() {\n        when(repo.save(any())).thenReturn(savedOrder);\n        Order result = service.create(validRequest);\n        assertThat(result.getStatus()).isEqualTo(PENDING);\n        verify(repo).save(any());\n    }\n}`,
    productionCode: `@SpringBootTest\n@Testcontainers\nclass OrderIntegrationTest {\n    @Container\n    static PostgreSQLContainer<?> postgres = new PostgreSQLContainer<>("postgres:16");\n    @Test\n    void shouldPersistOrder() {\n        ResponseEntity<OrderDto> response = restTemplate.postForEntity("/api/v1/orders", request, OrderDto.class);\n        assertThat(response.getStatusCode()).isEqualTo(CREATED);\n    }\n}`,
    bestPractices: ["Follow testing pyramid proportions", "Use TestContainers over H2 for integration tests", "Test behavior, not implementation", "Run tests in CI on every PR"],
    commonMistakes: ["Testing private methods", "Flaky tests with Thread.sleep", "No test isolation (shared state)", "100% coverage obsession on trivial code"],
    interviewQuestions: [
      { question: "Mock vs Stub vs Fake?", answer: "Mock: verifies interactions (verify calls). Stub: returns canned responses. Fake: working implementation (in-memory DB). Use mocks for behavior verification; fakes for integration tests." },
    ],
  },
  "Observability Stack": {
    overview: "Observability = Metrics + Logs + Traces. Prometheus/Grafana for metrics, ELK/Loki for logs, Jaeger/Zipkin for distributed tracing. Enables debugging production systems.",
    whyItExists: "Microservices create complex failure paths. You can't debug what you can't see. Observability provides the three pillars to understand system behavior in production.",
    internalWorking: "Metrics: time-series counters/gauges scraped by Prometheus. Logs: structured JSON aggregated by Loki/ELK. Traces: OpenTelemetry spans showing request flow across services.",
    realWorldUsage: "Micrometer exports metrics to Prometheus. Grafana dashboards for SLA monitoring. Structured logging with correlation IDs. OpenTelemetry traces across CommerceX services.",
    codeExample: `@RestController\n@Slf4j\npublic class OrderController {\n    private final Counter orderCounter = Counter.builder("orders.created")\n        .tag("service", "order-service").register(meterRegistry);\n    @PostMapping\n    public OrderDto create(@RequestBody CreateOrderRequest req) {\n        log.info("Creating order", kv("customerId", req.customerId()));\n        orderCounter.increment();\n        return orderService.create(req);\n    }\n}`,
    productionCode: `# Grafana alert\n- alert: HighErrorRate\n  expr: rate(http_server_errors_total[5m]) > 0.05\n  for: 2m\n  annotations:\n    summary: "Error rate above 5% for {{ $labels.service }}"`,
    bestPractices: ["Structured JSON logging with correlation IDs", "RED metrics (Rate, Errors, Duration)", "Alert on symptoms (latency), not causes (CPU)", "Distributed tracing across all services"],
    commonMistakes: ["String-format logging (hard to query)", "Too many alerts (alert fatigue)", "No correlation ID propagation", "Metrics without labels/dimensions"],
    interviewQuestions: [
      { question: "Metrics vs Logs vs Traces?", answer: "Metrics: aggregated numbers over time (request rate, error %). Logs: discrete events with context. Traces: request journey across services with timing. Use all three together for full observability." },
    ],
  },
};
