/** Rich content for roadmap levels 1–6 */

export const LEVELS_01_06 = {
  "Variables & Data Types": {
    overview: "Java is statically typed — every variable has a declared type checked at compile time. Primitives (int, double, boolean) live on the stack; objects live on the heap with references on the stack.",
    whyItExists: "Type safety prevents entire classes of runtime bugs. Explicit types make APIs self-documenting and enable IDE tooling, refactoring, and compile-time validation at scale.",
    internalWorking: "The JVM stores primitives directly in stack frames. Reference types store a pointer (reference) to heap objects. Autoboxing wraps primitives in wrapper classes (Integer, Double) when collections require objects.",
    realWorldUsage: "Payment services use BigDecimal for money (never float). IDs use long/UUID. Feature flags use boolean. Amazon order pipelines validate types at API boundaries before processing.",
    codeExample: `int quantity = 5;\nlong orderId = 9_001_234_567L;\nBigDecimal price = new BigDecimal("19.99");\nString sku = "PROD-001";\n\n// Wrapper autoboxing\nList<Integer> counts = List.of(1, 2, 3);`,
    productionCode: `@Service\npublic class PricingService {\n    public Money calculateTotal(List<LineItem> items) {\n        return items.stream()\n            .map(i -> i.getPrice().multiply(BigDecimal.valueOf(i.getQty())))\n            .reduce(Money.ZERO, Money::add);\n    }\n}`,
    bestPractices: ["Use BigDecimal for currency", "Prefer long over int for IDs", "Use meaningful variable names", "Declare variables in the smallest scope"],
    commonMistakes: ["Using float/double for money", "Comparing strings with ==", "Null wrapper objects in arithmetic", "Choosing wrong numeric type causing overflow"],
    interviewQuestions: [
      { question: "Difference between == and equals()?", answer: "== compares references for objects, values for primitives. equals() compares logical equality (must be overridden). Always use equals() for String/content comparison." },
      { question: "Why BigDecimal for financial calculations?", answer: "float/double use binary floating point causing rounding errors (0.1 + 0.2 ≠ 0.3). BigDecimal provides exact decimal arithmetic required for payments." },
    ],
    links: [{ title: "Java Primitive Types", url: "https://docs.oracle.com/javase/tutorial/java/nutsandbolts/datatypes.html", type: "docs" }],
  },
  "Control Flow & Methods": {
    overview: "Control flow (if/else, switch, loops) directs program execution. Methods encapsulate reusable logic with parameters, return types, and access modifiers.",
    whyItExists: "Without structured control flow, code becomes unmaintainable spaghetti. Methods enable decomposition, testing, and the Single Responsibility Principle.",
    internalWorking: "The JVM executes bytecode sequentially. Branch instructions (ifeq, goto) handle conditionals. Method calls push a new stack frame; returns pop it. Switch on String uses hash lookups (since Java 7).",
    realWorldUsage: "Order state machines use switch expressions. Retry loops wrap external API calls. Private helper methods keep service classes under 200 lines at Stripe and Netflix.",
    codeExample: `public OrderStatus processOrder(Order order) {\n    return switch (order.getState()) {\n        case PENDING -> validateAndSubmit(order);\n        case PAID -> OrderStatus.SHIPPED;\n        case CANCELLED -> OrderStatus.REFUNDED;\n        default -> throw new IllegalStateException("Unknown: " + order.getState());\n    };\n}`,
    productionCode: `@Retryable(maxAttempts = 3, backoff = @Backoff(delay = 500))\npublic PaymentResult charge(PaymentRequest req) {\n    validate(req);\n    return paymentGateway.charge(req);\n}`,
    bestPractices: ["Keep methods under 20 lines when possible", "Use switch expressions over if-else chains", "Validate inputs at method entry", "Prefer early returns over deep nesting"],
    commonMistakes: ["Missing break in switch (pre-Java 14)", "Modifying loop counter inside enhanced for", "God methods with 500+ lines", "Swallowing exceptions in catch blocks"],
    interviewQuestions: [
      { question: "Enhanced for vs traditional for loop?", answer: "Enhanced for (for-each) is read-only over Iterable/array, cleaner syntax. Traditional for gives index control and allows modification. Use for-each by default." },
    ],
  },
  "Classes & Objects": {
    overview: "Classes are blueprints; objects are runtime instances. Fields hold state, methods define behavior. Constructors initialize object state.",
    whyItExists: "OOP models real-world entities (User, Order, Account). Encapsulation hides internal state and exposes controlled interfaces — essential for large codebases.",
    internalWorking: "new keyword allocates heap memory, invokes constructor, returns reference. Instance fields live in the object; static fields belong to the class. this refers to current instance.",
    realWorldUsage: "Domain models (Product, Transfer, Invoice) are POJOs/entities. DTOs transfer data between layers. Value objects (Money, Email) enforce invariants at construction.",
    codeExample: `public record Money(BigDecimal amount, Currency currency) {\n    public Money {\n        if (amount.compareTo(BigDecimal.ZERO) < 0)\n            throw new IllegalArgumentException("Negative amount");\n    }\n    public Money add(Money other) {\n        requireSameCurrency(other);\n        return new Money(amount.add(other.amount), currency);\n    }\n}`,
    productionCode: `@Entity\n@Table(name = "products")\npublic class Product {\n    @Id @GeneratedValue\n    private Long id;\n    @Column(nullable = false)\n    private String name;\n    @Embedded\n    private Money price;\n}`,
    bestPractices: ["Use records for immutable value objects", "Make fields private, expose via getters", "Validate in constructor", "Prefer composition over inheritance"],
    commonMistakes: ["Public mutable fields", "Anemic domain models with no behavior", "Not overriding equals/hashCode for entities", "Leaking internal collections"],
    interviewQuestions: [
      { question: "What is the difference between class and object?", answer: "A class is a template defining structure and behavior. An object is a concrete instance created at runtime with its own state in memory." },
    ],
  },
  "Inheritance & Polymorphism": {
    overview: "Inheritance (extends) reuses parent class behavior. Polymorphism allows treating subclasses as their parent type — enabling runtime method dispatch.",
    whyItExists: "Polymorphism enables plug-in architectures: swap implementations (PaymentProcessor, NotificationSender) without changing client code. Open/Closed Principle depends on it.",
    internalWorking: "JVM uses dynamic dispatch (vtable) for instance methods. At runtime, the actual object type determines which method runs. Static methods and fields are not polymorphic.",
    realWorldUsage: "Payment gateways implement PaymentProcessor interface. Notification channels extend AbstractNotifier. Spring uses polymorphism extensively via @Autowired interfaces.",
    codeExample: `public interface PaymentProcessor {\n    PaymentResult process(Payment payment);\n}\n\n@Service\npublic class StripeProcessor implements PaymentProcessor {\n    public PaymentResult process(Payment p) { /* Stripe API */ }\n}\n\n@Service\npublic class PayPalProcessor implements PaymentProcessor {\n    public PaymentResult process(Payment p) { /* PayPal API */ }\n}`,
    productionCode: `@Service\n@RequiredArgsConstructor\npublic class CheckoutService {\n    private final PaymentProcessor processor; // Injected implementation\n    public Receipt checkout(Cart cart) {\n        return processor.process(cart.toPayment());\n    }\n}`,
    bestPractices: ["Program to interfaces, not implementations", "Use @Override annotation", "Favor composition over deep inheritance", "Keep inheritance hierarchies shallow (2-3 levels)"],
    commonMistakes: ["Deep inheritance trees", "Violating Liskov Substitution Principle", "Calling super in wrong order", "Using inheritance for code reuse only"],
    interviewQuestions: [
      { question: "Explain runtime polymorphism with an example.", answer: "PaymentProcessor p = new StripeProcessor(); p.process(payment) calls Stripe's implementation at runtime despite the interface type. JVM resolves via virtual method table." },
    ],
  },
  "Collections Framework": {
    overview: "Java Collections (List, Set, Map, Queue) provide standardized data structures. ArrayList, HashMap, HashSet are the workhorses; choose based on access patterns.",
    whyItExists: "Raw arrays are fixed-size and lack APIs. Collections provide dynamic sizing, iteration, sorting, streaming, and thread-safe variants for enterprise data handling.",
    internalWorking: "ArrayList: dynamic array, O(1) get, O(n) insert middle. HashMap: bucket array + linked list/tree, O(1) average get. HashSet wraps HashMap. Fail-fast iterators detect concurrent modification.",
    realWorldUsage: "HashMap caches product lookups. ArrayList holds order line items. LinkedHashMap maintains insertion order for audit logs. ConcurrentHashMap in multi-threaded caches.",
    codeExample: `Map<String, Product> catalog = new HashMap<>();\ncatalog.put("SKU-001", new Product("Widget", 9.99));\n\nList<Order> recent = orders.stream()\n    .filter(o -> o.getDate().isAfter(yesterday))\n    .sorted(comparing(Order::getDate).reversed())\n    .limit(100)\n    .toList();`,
    productionCode: `@Cacheable("products")\npublic Product findBySku(String sku) {\n    return productRepository.findById(sku)\n        .orElseThrow(() -> new ProductNotFoundException(sku));\n}`,
    bestPractices: ["Program to interfaces (List, Map)", "Specify initial capacity for large collections", "Use immutable collections (List.of) for constants", "Choose ConcurrentHashMap for shared mutable state"],
    commonMistakes: ["Using raw types without generics", "Modifying collection during iteration", "Using Vector/Hashtable (legacy synchronized)", "Wrong Map implementation for use case"],
    interviewQuestions: [
      { question: "HashMap vs TreeMap?", answer: "HashMap: O(1) average, no ordering. TreeMap: O(log n), sorted by key. Use HashMap for general lookup; TreeMap when sorted iteration needed." },
      { question: "How does HashMap handle collisions?", answer: "Same bucket: linked list (Java 8+) converts to red-black tree when bucket size exceeds 8. Uses hashCode() for bucket, equals() for key match." },
    ],
  },
  "Streams & Optional": {
    overview: "Streams provide declarative data processing (filter, map, reduce). Optional eliminates null checks by wrapping possibly-absent values.",
    whyItExists: "Imperative loops are verbose and error-prone. Streams enable parallel processing and readable pipelines. Optional makes absence explicit in APIs.",
    internalWorking: "Streams are lazy — intermediate ops build a pipeline, terminal ops trigger execution. Optional is a container with isPresent(), orElse(), map(), flatMap(). Never use get() without isPresent().",
    realWorldUsage: "Transform order DTOs to responses. Aggregate revenue by category. Optional.orElseThrow for repository lookups. Parallel streams for batch processing (use carefully).",
    codeExample: `Optional<User> user = userRepository.findByEmail(email);\nString name = user.map(User::getName).orElse("Guest");\n\ndouble total = orders.stream()\n    .filter(o -> o.getStatus() == PAID)\n    .mapToDouble(Order::getTotal)\n    .sum();`,
    productionCode: `public OrderSummary toSummary(Order order) {\n    return OrderSummary.builder()\n        .id(order.getId())\n        .customer(order.getCustomer().map(Customer::getName).orElse("Unknown"))\n        .items(order.getItems().stream().map(this::toItemDto).toList())\n        .build();\n}`,
    bestPractices: ["Use Optional as return type, not field/parameter", "Prefer method references (Order::getTotal)", "Avoid parallel streams for small data", "Use collect with downstream for grouping"],
    commonMistakes: ["Calling .get() on empty Optional", "Using streams for simple loops", "Stateful operations in parallel streams", "Returning null instead of Optional.empty()"],
    interviewQuestions: [
      { question: "Intermediate vs terminal stream operations?", answer: "Intermediate (filter, map) return Stream and are lazy. Terminal (collect, forEach, reduce) trigger execution and produce result or side effect." },
    ],
  },
  "Exception Handling": {
    overview: "Exceptions signal error conditions. Checked exceptions must be declared/handled; unchecked (RuntimeException) propagate freely. try-catch-finally and try-with-resources manage cleanup.",
    whyItExists: "Errors happen — network failures, invalid input, DB timeouts. Structured exception handling separates error paths from happy paths and ensures resource cleanup.",
    internalWorking: "throw creates exception object and unwinds stack until catch matches. try-with-resources calls AutoCloseable.close() automatically. Suppressed exceptions track errors during close.",
    realWorldUsage: "@ControllerAdvice maps exceptions to HTTP responses. Custom exceptions (OrderNotFoundException) carry error codes. Retry logic catches transient failures.",
    codeExample: `try (Connection conn = dataSource.getConnection();\n     PreparedStatement ps = conn.prepareStatement(SQL)) {\n    ps.setLong(1, orderId);\n    return ps.executeQuery();\n} catch (SQLException e) {\n    throw new DataAccessException("Failed to fetch order " + orderId, e);\n}`,
    productionCode: `@ExceptionHandler(OrderNotFoundException.class)\npublic ResponseEntity<ErrorResponse> handleNotFound(OrderNotFoundException ex) {\n    return ResponseEntity.status(404)\n        .body(new ErrorResponse("ORDER_NOT_FOUND", ex.getMessage()));\n}`,
    bestPractices: ["Catch specific exceptions, not Exception", "Always include cause when re-throwing", "Use try-with-resources for closables", "Fail fast with meaningful messages"],
    commonMistakes: ["Empty catch blocks", "Using exceptions for control flow", "Catching Throwable/Error", "Logging and re-throwing same exception"],
    interviewQuestions: [
      { question: "Checked vs unchecked exceptions?", answer: "Checked (IOException): compiler enforces handling. Unchecked (RuntimeException): optional handling. Use checked for recoverable external failures; unchecked for programming errors." },
    ],
  },
  "File I/O & NIO": {
    overview: "java.io provides stream-based I/O; java.nio offers channels, buffers, and memory-mapped files for high-performance I/O.",
    whyItExists: "Services read config files, write logs, process CSV imports, and stream large files. NIO enables non-blocking I/O critical for high-throughput systems.",
    internalWorking: "Streams are byte/char oriented. NIO uses ByteBuffer and Channels. Files.readString/writeString (Java 11+) simplify file ops. Path API replaces File class.",
    realWorldUsage: "Load application.yml at startup. Export transaction reports to CSV. Process bulk imports with BufferedReader. NIO for log aggregation pipelines.",
    codeExample: `Path config = Path.of("config", "app.yml");\nString content = Files.readString(config, StandardCharsets.UTF_8);\n\nFiles.lines(Path.of("orders.csv"))\n    .skip(1)\n    .map(line -> line.split(","))\n    .forEach(this::processRow);`,
    productionCode: `@Scheduled(cron = "0 0 * * * *")\npublic void exportHourlyReport() {\n    Path output = Path.of("/exports", "orders-" + Instant.now() + ".csv");\n    try (var writer = Files.newBufferedWriter(output)) {\n        orderRepository.streamAll().forEach(o -> writer.write(o.toCsv()));\n    }\n}`,
    bestPractices: ["Always specify charset (UTF-8)", "Use try-with-resources", "Prefer Path over File", "Buffer large reads/writes"],
    commonMistakes: ["Not closing streams (resource leak)", "Platform-default charset assumptions", "Reading entire large file into memory", "Ignoring IOException in lambdas"],
    interviewQuestions: [
      { question: "NIO vs traditional I/O?", answer: "Traditional I/O is stream-based, blocking. NIO uses buffers/channels, supports non-blocking and memory-mapped files. NIO better for high-concurrency servers." },
    ],
  },
  "Generics": {
    overview: "Generics add compile-time type safety to classes, interfaces, and methods. Type parameters (T, E, K, V) eliminate casts and catch errors at compile time.",
    whyItExists: "Before generics, collections stored Object requiring casts and risking ClassCastException at runtime. Generics move type checking to compile time.",
    internalWorking: "Type erasure removes generic info at runtime — List<String> becomes List. Wildcards (? extends T, ? super T) provide flexibility. PECS: Producer Extends, Consumer Super.",
    realWorldUsage: "Repository<T, ID> base classes. ApiResponse<T> wrappers. Event handlers with typed payloads. Generic mappers between DTO and entity.",
    codeExample: `public class Repository<T extends Entity, ID> {\n    public Optional<T> findById(ID id) { /* ... */ }\n    public T save(T entity) { /* ... */ }\n}\n\npublic <T> List<T> filter(List<T> items, Predicate<T> predicate) {\n    return items.stream().filter(predicate).toList();\n}`,
    productionCode: `public record ApiResponse<T>(String status, T data, Instant timestamp) {\n    public static <T> ApiResponse<T> ok(T data) {\n        return new ApiResponse<>("success", data, Instant.now());\n    }\n}`,
    bestPractices: ["Use bounded wildcards for API flexibility", "Avoid raw types", "Prefer List<T> over T[] for generics", "Document type parameter constraints"],
    commonMistakes: ["Generic array creation", "Using <?> when specific type known", "Over-complex generic signatures", "Ignoring PECS principle"],
    interviewQuestions: [
      { question: "What is type erasure?", answer: "Compiler removes generic type parameters at runtime. List<String> and List<Integer> both become List. Enables backward compatibility but limits runtime type introspection." },
    ],
  },
  "Annotations & Reflection": {
    overview: "Annotations add metadata to code (@Override, @Entity, @Autowired). Reflection inspects and manipulates classes at runtime — fields, methods, annotations.",
    whyItExists: "Frameworks (Spring, JPA, JUnit) use annotations for declarative configuration. Reflection enables dependency injection, ORM mapping, and test discovery without boilerplate.",
    internalWorking: "Annotations are interfaces extending Annotation. Retention policy controls lifecycle (SOURCE, CLASS, RUNTIME). Reflection API: Class.forName(), getDeclaredMethods(), setAccessible().",
    realWorldUsage: "@RestController defines API endpoints. @Transactional manages DB transactions. @Test discovers test methods. Custom @Audited triggers logging aspects.",
    codeExample: `@Target(ElementType.METHOD)\n@Retention(RetentionPolicy.RUNTIME)\npublic @interface Audited {\n    String action();\n}\n\n@Audited(action = "CREATE_ORDER")\npublic Order createOrder(CreateOrderRequest req) { /* ... */ }`,
    productionCode: `@Aspect @Component\npublic class AuditAspect {\n    @Around("@annotation(audited)")\n    public Object audit(ProceedingJoinPoint jp, Audited audited) throws Throwable {\n        log.info("Action: {}", audited.action());\n        return jp.proceed();\n    }\n}`,
    bestPractices: ["Create custom annotations for cross-cutting concerns", "Use RUNTIME retention for framework processing", "Minimize reflection in hot paths", "Prefer compile-time annotation processors when possible"],
    commonMistakes: ["Overusing reflection (performance cost)", "Breaking encapsulation with setAccessible", "Annotation proliferation without documentation", "Runtime retention on compile-only annotations"],
    interviewQuestions: [
      { question: "How does Spring find @Autowired fields?", answer: "At startup, Spring scans classpath, uses reflection to find @Component classes, inspects fields/constructors for @Autowired, and injects matching beans from the ApplicationContext." },
    ],
  },
  "Threads & Executors": {
    overview: "Threads enable concurrent execution. ExecutorService manages thread pools, avoiding manual thread creation/destruction. CompletableFuture composes async operations.",
    whyItExists: "Modern services handle thousands of concurrent requests. Thread pools reuse threads efficiently. Async processing prevents blocking I/O from stalling the entire application.",
    internalWorking: "Each thread has its own stack. ExecutorService maintains a work queue and thread pool. CompletableFuture chains async stages with thenApply, thenCompose, allOf.",
    realWorldUsage: "Parallel API calls to payment + inventory + shipping. @Async methods in Spring. Batch job processing with fixed thread pools. CompletableFuture for timeout handling.",
    codeExample: `ExecutorService pool = Executors.newFixedThreadPool(10);\ntry {\n    Future<OrderResult> future = pool.submit(() -> processOrder(order));\n    OrderResult result = future.get(5, TimeUnit.SECONDS);\n} finally { pool.shutdown(); }`,
    productionCode: `@Async("orderExecutor")\npublic CompletableFuture<OrderConfirmation> processAsync(Order order) {\n    return CompletableFuture.supplyAsync(() -> {\n        validateInventory(order);\n        chargePayment(order);\n        return confirm(order);\n    });\n}`,
    bestPractices: ["Use ExecutorService, never raw Thread", "Size pools based on workload (CPU vs I/O bound)", "Always shutdown executors", "Use CompletableFuture for composition"],
    commonMistakes: ["Unbounded thread pools causing OOM", "Sharing mutable state without synchronization", "Blocking inside @Async methods", "Ignoring Future.get() timeouts"],
    interviewQuestions: [
      { question: "Difference between Thread and ExecutorService?", answer: "Thread: manual lifecycle, expensive creation. ExecutorService: managed pool, work queue, reuse, graceful shutdown. Always prefer ExecutorService in production." },
    ],
  },
  "Concurrent Collections & Locks": {
    overview: "java.util.concurrent provides thread-safe collections (ConcurrentHashMap, CopyOnWriteArrayList) and locks (ReentrantLock, ReadWriteLock, Semaphore).",
    whyItExists: "Standard collections fail under concurrent modification. synchronized blocks are coarse-grained. JUC provides fine-grained, high-performance concurrency primitives.",
    internalWorking: "ConcurrentHashMap uses segment/bucket locking. ReentrantLock supports tryLock, fairness, conditions. volatile ensures visibility. AtomicInteger provides lock-free CAS operations.",
    realWorldUsage: "ConcurrentHashMap for in-memory rate limiters. ReadWriteLock for cache read-heavy workloads. CountDownLatch for service startup coordination. Semaphore for connection pooling.",
    codeExample: `ConcurrentHashMap<String, AtomicInteger> rateLimits = new ConcurrentHashMap<>();\n\npublic boolean allowRequest(String clientId) {\n    AtomicInteger count = rateLimits.computeIfAbsent(clientId, k -> new AtomicInteger());\n    return count.incrementAndGet() <= MAX_REQUESTS;\n}`,
    productionCode: `private final ReadWriteLock lock = new ReentrantReadWriteLock();\n\npublic Product getProduct(String id) {\n    lock.readLock().lock();\n    try { return cache.get(id); }\n    finally { lock.readLock().unlock(); }\n}`,
    bestPractices: ["Prefer JUC collections over synchronized wrappers", "Use Atomic* for simple counters", "Minimize lock scope", "Document thread-safety guarantees"],
    commonMistakes: ["Synchronizing on String literals", "Deadlock from lock ordering", "Using synchronized everywhere (performance)", "ConcurrentHashMap size() during concurrent writes"],
    interviewQuestions: [
      { question: "How does ConcurrentHashMap achieve thread safety?", answer: "Bucket-level locking (not whole map). Reads mostly lock-free. Writes lock only affected bucket. Java 8+ uses synchronized first node or tree bin." },
    ],
  },
};
