/** Rich content for roadmap levels 7–12 */

export const LEVELS_07_12 = {
  "JVM Memory Model": {
    overview: "The JVM divides memory into heap (objects), stack (method frames), metaspace (class metadata), and native memory. Understanding this layout is essential for debugging memory issues.",
    whyItExists: "Memory leaks and OOM errors are the #1 production incidents in Java services. Knowing where objects live helps diagnose GC pressure, stack overflows, and metaspace exhaustion.",
    internalWorking: "Stack: local variables, one per thread. Heap: Eden + Survivor + Old gen for objects. Metaspace stores class definitions (replaced PermGen in Java 8). TLAB (Thread Local Allocation Buffer) optimizes allocation.",
    realWorldUsage: "Heap dumps analyzed with Eclipse MAT at Netflix. Stack traces debug infinite recursion. Metaspace tuning for apps with dynamic class loading (Spring, Hibernate).",
    codeExample: `// Stack overflow example (avoid!)\nvoid recurse() { recurse(); }\n\n// Heap allocation\nList<byte[]> leak = new ArrayList<>();\nwhile (true) leak.add(new byte[1024 * 1024]); // OOM`,
    productionCode: `// JVM flags for production\n// -Xms2g -Xmx2g -XX:+UseG1GC\n// -XX:MaxMetaspaceSize=256m\n// -XX:+HeapDumpOnOutOfMemoryError`,
    bestPractices: ["Set -Xms equal to -Xmx to avoid resize pauses", "Monitor heap usage with metrics", "Use object pooling only when profiled necessary", "Analyze heap dumps, don't guess"],
    commonMistakes: ["Setting heap too large (long GC pauses)", "Ignoring metaspace limits", "Creating unnecessary object allocations in hot loops", "Not monitoring GC logs"],
    interviewQuestions: [
      { question: "Stack vs Heap in JVM?", answer: "Stack: thread-local, stores frames/primitives/references, LIFO, fast. Heap: shared, stores objects, GC-managed, slower allocation. StackOverflow vs OutOfMemoryError." },
    ],
  },
  "Garbage Collection & Tuning": {
    overview: "GC automatically reclaims unreachable objects. Collectors (G1, ZGC, Shenandoah) trade throughput vs latency. Tuning minimizes pause times for SLA-critical services.",
    whyItExists: "Manual memory management causes bugs. GC pauses directly impact p99 latency. Financial and e-commerce systems require sub-100ms GC pauses.",
    internalWorking: "Mark-and-sweep identifies reachable objects. Generational hypothesis: most objects die young. G1 divides heap into regions, collects incrementally. ZGC targets <10ms pauses.",
    realWorldUsage: "G1GC default for Java 17+. ZGC for ultra-low latency trading systems. GC log analysis with GCeasy/Grafana. Tuning after load testing, not before.",
    codeExample: `// JVM GC flags\n// G1: -XX:+UseG1GC -XX:MaxGCPauseMillis=200\n// ZGC: -XX:+UseZGC\n// Logging: -Xlog:gc*:file=gc.log:time,uptime,level,tags`,
    productionCode: `# Kubernetes pod with GC tuning\nenv:\n  - name: JAVA_OPTS\n    value: "-Xms1g -Xmx1g -XX:+UseG1GC -XX:MaxGCPauseMillis=100"`,
    bestPractices: ["Choose collector based on latency requirements", "Enable GC logging in production", "Tune after load testing with realistic data", "Monitor GC pause times in dashboards"],
    commonMistakes: ["Tuning without measurements", "Using CMS (removed in Java 14+)", "Setting MaxGCPauseMillis unrealistically low", "Ignoring GC cause analysis"],
    interviewQuestions: [
      { question: "How does G1 GC work?", answer: "Divides heap into equal regions. Tracks garbage per region. Prioritizes regions with most garbage. Mixed collections reclaim old gen incrementally. Targets pause time goal." },
    ],
  },
  "Creational & Structural Patterns": {
    overview: "Creational patterns (Factory, Builder, Singleton) control object creation. Structural patterns (Adapter, Decorator, Facade) compose objects into larger structures.",
    whyItExists: "Direct new() couples code to concrete classes. Patterns decouple creation from usage, enable testing with mocks, and simplify complex object construction.",
    internalWorking: "Factory Method: subclass decides object type. Builder: step-by-step construction with fluent API. Decorator: wraps object adding behavior. All rely on composition and interfaces.",
    realWorldUsage: "Builder for complex Order/Config objects. Factory for PaymentProcessor selection. Decorator for caching wrappers. Spring BeanFactory is a sophisticated factory.",
    codeExample: `Order order = Order.builder()\n    .customerId(123L)\n    .items(List.of(item1, item2))\n    .shippingAddress(address)\n    .build();`,
    productionCode: `@Configuration\npublic class PaymentConfig {\n    @Bean\n    @ConditionalOnProperty("payment.provider=stripe")\n    public PaymentProcessor stripeProcessor() {\n        return new StripeProcessor(stripeApiKey);\n    }\n}`,
    bestPractices: ["Use Builder for objects with 4+ parameters", "Prefer factory methods over constructors", "Avoid singleton abuse — use Spring scope", "Apply patterns to solve real problems, not speculatively"],
    commonMistakes: ["Singleton with mutable state", "Over-engineering with patterns everywhere", "God factory classes", "Builder without validation"],
    interviewQuestions: [
      { question: "Builder vs Factory pattern?", answer: "Factory: creates different types via common interface. Builder: constructs complex single object step-by-step. Use Builder for many optional params; Factory for type selection." },
    ],
  },
  "Behavioral & Enterprise Patterns": {
    overview: "Behavioral patterns (Strategy, Observer, Command) manage algorithms and communication. Enterprise patterns (Repository, DTO, Saga) address distributed system challenges.",
    whyItExists: "Business rules change frequently. Strategy enables swapping algorithms. Saga manages distributed transactions. Repository abstracts data access from domain logic.",
    internalWorking: "Strategy: interface + multiple implementations, selected at runtime. Observer: publish-subscribe via event listeners. Saga: sequence of local transactions with compensating actions.",
    realWorldUsage: "Strategy for pricing rules (discount, bulk, loyalty). Observer via Spring ApplicationEvent. Saga for order→payment→inventory in CommerceX. Repository pattern in every Spring Data app.",
    codeExample: `public interface PricingStrategy {\n    Money calculate(Cart cart);\n}\n\n@Service @RequiredArgsConstructor\npublic class CheckoutService {\n    private final Map<String, PricingStrategy> strategies;\n    public Money checkout(Cart cart, String strategyKey) {\n        return strategies.get(strategyKey).calculate(cart);\n    }\n}`,
    productionCode: `@Transactional\npublic void executeOrderSaga(Order order) {\n    try {\n        inventoryService.reserve(order);\n        paymentService.charge(order);\n        orderService.confirm(order);\n    } catch (PaymentException e) {\n        inventoryService.release(order); // compensating action\n        throw e;\n    }\n}`,
    bestPractices: ["Use Strategy over if-else for varying algorithms", "Keep sagas idempotent", "Publish domain events for decoupling", "Repository returns domain objects, not JDBC rows"],
    commonMistakes: ["Saga without compensation logic", "Observer chains causing circular events", "Anemic domain with all logic in services", "God strategy classes"],
    interviewQuestions: [
      { question: "Explain the Saga pattern.", answer: "Manages distributed transactions as sequence of local TXs. Each step has compensating action. On failure, previously completed steps are undone. Used in microservices instead of 2PC." },
    ],
  },
  "IoC & Dependency Injection": {
    overview: "Inversion of Control transfers object creation to a container. Dependency Injection provides dependencies from outside rather than objects creating them internally.",
    whyItExists: "new ConcreteClass() creates tight coupling and makes testing impossible. IoC enables swapping implementations, mocking in tests, and configuration-driven wiring.",
    internalWorking: "Spring ApplicationContext scans @Component classes, resolves @Autowired dependencies by type/name, manages bean lifecycle (singleton by default), and injects via constructor/setter/field.",
    realWorldUsage: "Every Spring Boot service uses constructor injection. @MockBean in tests replaces real dependencies. @Profile switches implementations per environment.",
    codeExample: `@Service\n@RequiredArgsConstructor // Lombok generates constructor injection\npublic class OrderService {\n    private final OrderRepository repository;\n    private final PaymentClient paymentClient;\n    private final EventPublisher events;\n}`,
    productionCode: `@Configuration\npublic class AppConfig {\n    @Bean\n    public RestTemplate restTemplate(RestTemplateBuilder builder) {\n        return builder.connectTimeout(Duration.ofSeconds(5))\n            .readTimeout(Duration.ofSeconds(10)).build();\n    }\n}`,
    bestPractices: ["Always use constructor injection", "Program to interfaces", "One constructor per class (implicit @Autowired)", "Use @ConfigurationProperties over @Value"],
    commonMistakes: ["Field injection (hard to test)", "Circular dependencies", "Too many constructor parameters (>7)", "Creating beans manually outside Spring"],
    interviewQuestions: [
      { question: "Constructor vs Field injection?", answer: "Constructor: immutable, testable, required deps explicit, recommended. Field: uses reflection, hides dependencies, harder to test. Always prefer constructor injection." },
    ],
  },
  "AOP & Spring Context": {
    overview: "Aspect-Oriented Programming separates cross-cutting concerns (logging, security, transactions) from business logic. Spring Context is the IoC container managing all beans.",
    whyItExists: "Scattering logging/security/transaction code across every method violates DRY. AOP centralizes these concerns. ApplicationContext provides enterprise services beyond basic DI.",
    internalWorking: "AOP uses proxies (JDK dynamic or CGLIB). @Aspect classes define @Before/@After/@Around advice on pointcuts. ApplicationContext adds event publishing, resource loading, i18n over BeanFactory.",
    realWorldUsage: "@Transactional is AOP — Spring wraps methods in TX boundaries. @Cacheable adds caching proxy. Custom @Audited aspect for compliance logging. Context events for startup hooks.",
    codeExample: `@Aspect @Component @Slf4j\npublic class LoggingAspect {\n    @Around("@within(org.springframework.web.bind.annotation.RestController)")\n    public Object logApiCall(ProceedingJoinPoint jp) throws Throwable {\n        log.info("API: {}.{}", jp.getSignature().getDeclaringTypeName(), jp.getSignature().getName());\n        return jp.proceed();\n    }\n}`,
    productionCode: `@Transactional(isolation = Isolation.READ_COMMITTED, rollbackFor = Exception.class)\npublic void transferFunds(TransferRequest req) {\n    accountService.debit(req.getFrom(), req.getAmount());\n    accountService.credit(req.getTo(), req.getAmount());\n}`,
    bestPractices: ["Use @Transactional on service layer, not repositories", "Keep aspects focused (single concern)", "Understand proxy limitations (self-invocation)", "Use ApplicationEventPublisher for decoupled notifications"],
    commonMistakes: ["@Transactional on private methods (won't work)", "Self-invocation bypassing proxy", "Overusing AOP for business logic", "Too broad pointcut expressions"],
    interviewQuestions: [
      { question: "Why doesn't @Transactional work on self-invocation?", answer: "Spring AOP uses proxies. this.method() calls target directly, bypassing proxy. Fix: inject self, use AspectJ compile-time weaving, or extract to separate bean." },
    ],
  },
  "Spring Boot Fundamentals": {
    overview: "Spring Boot auto-configures Spring applications based on classpath dependencies. Starters bundle common dependencies. Embedded servers enable standalone JARs.",
    whyItExists: "Spring XML configuration was verbose and error-prone. Boot reduces boilerplate to near-zero, enabling microservices that start in seconds with sensible defaults.",
    internalWorking: "@SpringBootApplication = @Configuration + @EnableAutoConfiguration + @ComponentScan. Auto-config classes in META-INF/spring apply conditionally (@ConditionalOnClass). Actuator exposes health/metrics endpoints.",
    realWorldUsage: "Every microservice starts as spring init + dependencies. spring-boot-starter-web for REST. spring-boot-starter-data-jpa for DB. Actuator for K8s health probes.",
    codeExample: `@SpringBootApplication\npublic class OrderServiceApplication {\n    public static void main(String[] args) {\n        SpringApplication.run(OrderServiceApplication.class, args);\n    }\n}`,
    productionCode: `@RestController\n@RequestMapping("/api/v1/orders")\n@RequiredArgsConstructor\npublic class OrderController {\n    private final OrderService orderService;\n    @GetMapping("/{id}")\n    public OrderResponse get(@PathVariable Long id) {\n        return orderService.findById(id);\n    }\n}`,
    bestPractices: ["Use spring-boot-starter-* dependencies", "Externalize config via application.yml", "Enable Actuator health endpoints", "Use @SpringBootTest for integration tests"],
    commonMistakes: ["Not excluding unused auto-configurations", "Hardcoding config values", "Running with dev profile in production", "Ignoring startup failure analysis"],
    interviewQuestions: [
      { question: "How does Spring Boot auto-configuration work?", answer: "Scans META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports. Each config class uses @ConditionalOn* annotations. Applies only when matching classes/properties exist on classpath." },
    ],
  },
  "Configuration & Profiles": {
    overview: "Externalized configuration via application.yml/properties. Profiles (dev, staging, prod) activate environment-specific settings. @ConfigurationProperties binds typed config objects.",
    whyItExists: "Hardcoded config prevents environment promotion. 12-factor app mandates config in environment. Profiles enable one codebase deployed everywhere with different settings.",
    internalWorking: "Property resolution: command line > env vars > application-{profile}.yml > application.yml. @ConfigurationProperties validates and binds prefix groups. @Profile conditionally loads beans.",
    realWorldUsage: "application-prod.yml with RDS endpoints. SPRING_PROFILES_ACTIVE=prod in K8s. @ConfigurationProperties for KafkaSettings, RedisConfig. Vault/AWS Secrets Manager for sensitive values.",
    codeExample: `@ConfigurationProperties(prefix = "app.kafka")\n@Validated\npublic record KafkaSettings(\n    @NotBlank String bootstrapServers,\n    @Min(1) int retries,\n    @NotBlank String topic\n) {}`,
    productionCode: `# application-prod.yml\nspring:\n  datasource:\n    url: jdbc:postgresql://\${DB_HOST}:5432/commercex\n  kafka:\n    bootstrap-servers: \${KAFKA_BROKERS}\napp:\n  kafka:\n    topic: order-events`,
    bestPractices: ["Never commit secrets to git", "Use @ConfigurationProperties over scattered @Value", "Validate config at startup", "Document all properties"],
    commonMistakes: ["Secrets in application.yml", "Missing profile-specific overrides", "Not validating config properties", "Using @Value for complex nested config"],
    interviewQuestions: [
      { question: "Property resolution order in Spring Boot?", answer: "Command line args > SPRING_APPLICATION_JSON > ServletConfig > JNDI > System properties > OS env vars > application-{profile}.properties > application.properties. Higher priority wins." },
    ],
  },
  "REST Principles & Controllers": {
    overview: "REST uses HTTP methods (GET, POST, PUT, DELETE) on resource URLs. Controllers map requests to handler methods returning JSON via @RestController.",
    whyItExists: "REST is the standard for microservice communication. Stateless HTTP enables caching, load balancing, and horizontal scaling. Uniform interface simplifies client integration.",
    internalWorking: "DispatcherServlet routes requests to @RequestMapping methods. HttpMessageConverter serializes/deserializes JSON. @PathVariable extracts URL params, @RequestBody deserializes JSON body.",
    realWorldUsage: "CommerceX catalog API: GET /products, POST /orders. FinFlow: POST /transfers. Versioning via /api/v1 prefix or Accept header. HATEOAS links in mature APIs.",
    codeExample: `@RestController\n@RequestMapping("/api/v1/products")\npublic class ProductController {\n    @GetMapping("/{id}")\n    public ResponseEntity<ProductDto> get(@PathVariable String id) {\n        return productService.findById(id)\n            .map(ResponseEntity::ok)\n            .orElse(ResponseEntity.notFound().build());\n    }\n    @PostMapping\n    @ResponseStatus(HttpStatus.CREATED)\n    public ProductDto create(@Valid @RequestBody CreateProductRequest req) { /* ... */ }\n}`,
    productionCode: `@GetMapping\npublic Page<ProductDto> list(\n    @RequestParam(defaultValue = "0") int page,\n    @RequestParam(defaultValue = "20") int size,\n    @RequestParam(required = false) String category) {\n    return productService.search(category, PageRequest.of(page, size));\n}`,
    bestPractices: ["Use proper HTTP methods and status codes", "Version your APIs (/api/v1)", "Return 201 + Location header on create", "Use pagination for list endpoints"],
    commonMistakes: ["Using GET for state changes", "Returning 200 for everything", "No API versioning strategy", "Exposing internal entity models directly"],
    interviewQuestions: [
      { question: "PUT vs PATCH?", answer: "PUT: replaces entire resource (idempotent). PATCH: partial update of specific fields. Use PUT for full updates, PATCH for partial modifications." },
    ],
  },
  "Validation & OpenAPI": {
    overview: "Bean Validation (@NotNull, @Size, @Email) validates request data declaratively. OpenAPI (Swagger) generates interactive API documentation from annotations.",
    whyItExists: "Invalid input is the top cause of 500 errors. Validation at the boundary prevents bad data reaching business logic. OpenAPI enables frontend/backend parallel development.",
    internalWorking: "@Valid triggers JSR-380 validation on @RequestBody. Violations throw MethodArgumentNotValidException. springdoc-openapi scans @Operation, @Schema annotations to generate spec.",
    realWorldUsage: "Validate payment amounts, email formats, required fields at API layer. Swagger UI for QA testing. Generated clients for frontend teams. Contract testing with OpenAPI spec.",
    codeExample: `public record CreateOrderRequest(\n    @NotNull Long customerId,\n    @NotEmpty @Size(max = 50) List<@Valid LineItem> items,\n    @NotBlank String shippingAddress\n) {}\n\npublic record LineItem(\n    @NotBlank String sku,\n    @Min(1) @Max(100) int quantity\n) {}`,
    productionCode: `@Operation(summary = "Create order", responses = {\n    @ApiResponse(responseCode = "201", description = "Order created"),\n    @ApiResponse(responseCode = "400", description = "Validation failed")\n})\n@PostMapping\npublic ResponseEntity<OrderDto> create(@Valid @RequestBody CreateOrderRequest req) { /* ... */ }`,
    bestPractices: ["Validate at API boundary", "Return structured error responses", "Keep OpenAPI spec in sync with code", "Use custom validators for business rules"],
    commonMistakes: ["Validation only on frontend", "Generic 400 error messages", "Outdated Swagger docs", "Validating in controller instead of DTO"],
    interviewQuestions: [
      { question: "How does @Valid work in Spring?", answer: "JSR-380 annotations on DTO fields. @Valid on @RequestBody triggers Hibernate Validator. Failures produce BindingResult/MethodArgumentNotValidException with field-level error details." },
    ],
  },
  "JPA Entities & Relationships": {
    overview: "JPA maps Java objects to database tables. @Entity defines models, @OneToMany/@ManyToOne/@ManyToMany define relationships. Hibernate is the default JPA provider.",
    whyItExists: "Raw JDBC is verbose and error-prone. ORM eliminates SQL boilerplate, manages object-relational impedance mismatch, and provides caching and lazy loading.",
    internalWorking: "EntityManager persists/flushes changes. Lazy loading via proxies (Hibernate). Cascade types control related entity persistence. @JoinColumn defines FK mapping.",
    realWorldUsage: "Order→OrderItems (@OneToMany). User→Orders (@OneToMany). Product→Category (@ManyToOne). FinFlow Account→Transactions. Spring Data JPA repositories abstract CRUD.",
    codeExample: `@Entity\npublic class Order {\n    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)\n    private Long id;\n    @ManyToOne(fetch = FetchType.LAZY)\n    private Customer customer;\n    @OneToMany(mappedBy = "order", cascade = CascadeType.ALL)\n    private List<OrderItem> items = new ArrayList<>();\n}`,
    productionCode: `public interface OrderRepository extends JpaRepository<Order, Long> {\n    @Query("SELECT o FROM Order o JOIN FETCH o.items WHERE o.id = :id")\n    Optional<Order> findByIdWithItems(@Param("id") Long id);\n}`,
    bestPractices: ["Use LAZY fetch by default", "Avoid bidirectional relationships when possible", "Use @JoinColumn explicitly", "Equals/hashCode on ID only for entities"],
    commonMistakes: ["EAGER fetch causing N+1 queries", "CascadeType.ALL on @ManyToMany", "Exposing entities in REST API", "Missing @Transactional on lazy loading"],
    interviewQuestions: [
      { question: "Lazy vs Eager loading?", answer: "Lazy: proxy loaded on access (default, efficient). Eager: loaded immediately with parent (can cause N+1, memory issues). Always default to LAZY, use JOIN FETCH when needed." },
    ],
  },
  "Query Optimization & Transactions": {
    overview: "Optimize JPA queries with JPQL, native SQL, projections, and fetch joins. @Transactional manages ACID properties with propagation and isolation levels.",
    whyItExists: "N+1 queries destroy performance at scale. Wrong transaction boundaries cause data corruption. Proper query design and TX management are critical for financial systems.",
    internalWorking: "Persistence context tracks entity changes. flush() syncs to DB. @Transactional creates proxy wrapping method in TX. Propagation controls nested TX behavior. Isolation prevents dirty reads.",
    realWorldUsage: "JOIN FETCH for order+items in one query. @Modifying for bulk updates. READ_COMMITTED for most services. REQUIRES_NEW for audit logging. Pessimistic lock for inventory.",
    codeExample: `@Transactional(readOnly = true)\npublic OrderDetail getOrderDetail(Long id) {\n    return orderRepo.findByIdWithItemsAndCustomer(id)\n        .map(this::toDetail)\n        .orElseThrow(() -> new OrderNotFoundException(id));\n}`,
    productionCode: `@Transactional\n@Lock(LockModeType.PESSIMISTIC_WRITE)\npublic void reserveInventory(String sku, int qty) {\n    Inventory inv = inventoryRepo.findBySkuForUpdate(sku);\n    if (inv.getAvailable() < qty) throw new InsufficientStockException(sku);\n    inv.reserve(qty);\n}`,
    bestPractices: ["Use readOnly=true for queries", "Keep transactions short", "Use @EntityGraph or JOIN FETCH to avoid N+1", "Choose isolation level based on requirements"],
    commonMistakes: ["Long-running transactions holding connections", "N+1 from lazy loading in loops", "Wrong propagation causing nested TX issues", "Not indexing queried columns"],
    interviewQuestions: [
      { question: "Explain @Transactional propagation REQUIRES_NEW.", answer: "Suspends current TX, creates new independent TX. Commits/rollbacks independently. Used for audit logs that must persist even if outer TX rolls back." },
    ],
  },
};
