/** Rich content for roadmap levels 13–17 */

export const LEVELS_13_17 = {
  "Database Design & Normalization": {
    overview: "Relational database design organizes data into normalized tables (1NF→3NF) eliminating redundancy. Primary keys, foreign keys, and constraints enforce integrity.",
    whyItExists: "Poor schema design causes data anomalies, update conflicts, and query performance issues. Normalization ensures consistency; strategic denormalization optimizes reads.",
    internalWorking: "1NF: atomic columns. 2NF: no partial dependencies. 3NF: no transitive dependencies. FK constraints enforce referential integrity. Indexes speed lookups at cost of write performance.",
    realWorldUsage: "CommerceX: products, categories, orders, order_items tables. FinFlow: accounts, transactions, ledger_entries. Separate read replicas for reporting queries.",
    codeExample: `CREATE TABLE orders (\n  id BIGSERIAL PRIMARY KEY,\n  customer_id BIGINT NOT NULL REFERENCES customers(id),\n  status VARCHAR(20) NOT NULL DEFAULT 'PENDING',\n  total DECIMAL(12,2) NOT NULL,\n  created_at TIMESTAMPTZ DEFAULT NOW()\n);`,
    productionCode: `-- Flyway migration V001__create_orders.sql\nCREATE INDEX idx_orders_customer ON orders(customer_id);\nCREATE INDEX idx_orders_status_created ON orders(status, created_at DESC);`,
    bestPractices: ["Normalize first, denormalize with measurement", "Use meaningful naming conventions", "Add created_at/updated_at to all tables", "Plan indexes based on query patterns"],
    commonMistakes: ["Storing comma-separated values in columns", "Missing foreign key constraints", "Over-normalizing causing excessive joins", "No migration tool (Flyway/Liquibase)"],
    interviewQuestions: [
      { question: "When would you denormalize?", answer: "When read performance critical and joins expensive. Examples: storing computed totals, duplicating customer name in orders for display. Always measure before denormalizing." },
    ],
  },
  "Indexing & Query Plans": {
    overview: "Indexes accelerate data retrieval. EXPLAIN ANALYZE reveals query execution plans. B-tree, hash, and GIN indexes serve different access patterns.",
    whyItExists: "Full table scans fail at millions of rows. Proper indexing reduces query time from seconds to milliseconds. Query plan analysis prevents production slowdowns.",
    internalWorking: "B-tree index: default, good for equality and range. Composite index: column order matters (leftmost prefix rule). EXPLAIN shows seq scan vs index scan, cost estimates.",
    realWorldUsage: "Composite index on (status, created_at) for order listing. Partial index on active users only. Covering indexes avoid table lookups. pg_stat_statements for slow query detection.",
    codeExample: `EXPLAIN ANALYZE\nSELECT * FROM orders\nWHERE customer_id = 123 AND status = 'PAID'\nORDER BY created_at DESC LIMIT 20;\n-- Look for: Index Scan vs Seq Scan, actual rows, execution time`,
    productionCode: `CREATE INDEX CONCURRENTLY idx_orders_customer_status\nON orders(customer_id, status, created_at DESC);\n-- CONCURRENTLY avoids locking in production`,
    bestPractices: ["Index columns in WHERE, JOIN, ORDER BY", "Use EXPLAIN ANALYZE before deploying", "Monitor index usage with pg_stat_user_indexes", "CREATE INDEX CONCURRENTLY in production"],
    commonMistakes: ["Indexing every column", "Wrong composite index column order", "Not analyzing after large data changes", "Ignoring unused indexes (write overhead)"],
    interviewQuestions: [
      { question: "What is a covering index?", answer: "Index containing all columns needed by query. Database reads only index, not table (index-only scan). Example: index on (customer_id, status, created_at) covers a filtered sorted listing query." },
    ],
  },
  "Service Decomposition": {
    overview: "Break monoliths into microservices bounded by business capabilities. Each service owns its data, deploys independently, and communicates via APIs or events.",
    whyItExists: "Monoliths become unmaintainable at scale. Microservices enable team autonomy, independent scaling, technology diversity, and fault isolation.",
    internalWorking: "Domain-Driven Design identifies bounded contexts. Each context becomes a service with its own DB. API gateway routes external requests. Event bus for async communication.",
    realWorldUsage: "CommerceX: user, catalog, cart, order, payment, inventory, notification services. FinFlow: account, transfer, fraud, compliance services. Strangler fig pattern for migration.",
    codeExample: `// Before: Monolith\nclass OrderService {\n    void createOrder() { /* user, inventory, payment, email all here */ }\n}\n// After: Microservices\norderService.create(order) → inventoryService.reserve()\n                       → paymentService.charge()\n                       → kafka.publish(OrderCreated)`,
    productionCode: `# CommerceX service boundaries\nuser-service:       users, auth, profiles\n catalog-service:    products, categories, search\ncart-service:       cart state (Redis)\norder-service:      order lifecycle, saga\npayment-service:    payment processing\ninventory-service:  stock management`,
    bestPractices: ["Decompose by business capability, not technical layer", "Database per service", "Design for failure", "Start with a modular monolith if unsure"],
    commonMistakes: ["Distributed monolith (tight coupling)", "Shared database between services", "Too many too-small services (nanoservices)", "Synchronous chains causing cascading failures"],
    interviewQuestions: [
      { question: "How do you decide service boundaries?", answer: "Use Domain-Driven Design bounded contexts. Each context has its own ubiquitous language, data, and team. Services should change independently. If two domains always change together, they may belong together." },
    ],
  },
  "Inter-Service Communication": {
    overview: "Microservices communicate via synchronous REST/gRPC or asynchronous messaging (Kafka). Each pattern has trade-offs in coupling, reliability, and complexity.",
    whyItExists: "Services must coordinate without shared memory. Communication patterns determine system resilience, latency, and consistency guarantees.",
    internalWorking: "Sync REST: request-response, tight coupling, simple. gRPC: binary protocol, streaming, faster. Async messaging: loose coupling, eventual consistency, buffering during outages.",
    realWorldUsage: "REST for user-facing queries. gRPC for internal high-throughput calls. Kafka for order events, inventory updates. Circuit breakers prevent cascade failures.",
    codeExample: `@FeignClient(name = "inventory-service")\npublic interface InventoryClient {\n    @PostMapping("/api/v1/inventory/reserve")\n    ReservationResponse reserve(@RequestBody ReserveRequest req);\n}`,
    productionCode: `@KafkaListener(topics = "order.created")\npublic void handleOrderCreated(OrderCreatedEvent event) {\n    inventoryService.reserve(event.getOrderId(), event.getItems());\n    notificationService.sendConfirmation(event.getCustomerId());\n}`,
    bestPractices: ["Prefer async for non-critical paths", "Use circuit breakers (Resilience4j)", "Implement timeouts and retries with backoff", "Design idempotent consumers"],
    commonMistakes: ["Sync chains of 5+ services", "No timeout on HTTP clients", "Chatty communication (many small calls)", "Missing idempotency keys"],
    interviewQuestions: [
      { question: "Sync vs async communication?", answer: "Sync: immediate response needed, simpler debugging, tighter coupling. Async: fire-and-forget, buffering, loose coupling, eventual consistency. Use async for events; sync for queries needing immediate data." },
    ],
  },
  "Service Discovery & Config": {
    overview: "Service discovery (Eureka, Consul) registers service instances dynamically. Centralized config (Spring Cloud Config) manages settings across environments.",
    whyItExists: "In K8s/cloud, service instances are ephemeral with dynamic IPs. Hardcoded URLs fail. Centralized config enables changing settings without redeployment.",
    internalWorking: "Services register on startup with discovery server. Clients query registry for healthy instances. Config server serves property files from Git. Bus refresh propagates changes.",
    realWorldUsage: "Eureka in Spring Cloud Netflix stack. K8s DNS replaces Eureka in cloud-native setups. Spring Cloud Config with Git backend. Vault for secrets.",
    codeExample: `# bootstrap.yml\nspring:\n  cloud:\n    config:\n      uri: http://config-server:8888\n      fail-fast: true\n    discovery:\n      enabled: true\neureka:\n  client:\n    serviceUrl:\n      defaultZone: http://eureka:8761/eureka/`,
    productionCode: `@RefreshScope\n@ConfigurationProperties(prefix = "feature")\npublic class FeatureFlags {\n    private boolean newCheckoutEnabled;\n    // Updated via POST /actuator/refresh\n}`,
    bestPractices: ["Use K8s service discovery in cloud deployments", "Encrypt secrets in config server", "Version config in Git", "Health checks for registration"],
    commonMistakes: ["Hardcoded service URLs", "Config server as single point of failure", "Not encrypting sensitive properties", "Stale registry entries without health checks"],
    interviewQuestions: [
      { question: "Eureka vs Kubernetes service discovery?", answer: "Eureka: application-level, client-side load balancing, Spring Cloud integration. K8s: DNS-based, built-in, no extra infra. Prefer K8s DNS in cloud-native; Eureka for hybrid/on-prem." },
    ],
  },
  "API Gateway & Circuit Breakers": {
    overview: "API Gateway is the single entry point routing, authenticating, and rate-limiting requests. Circuit breakers prevent cascade failures by stopping calls to failing services.",
    whyItExists: "Clients shouldn't know about internal service topology. Gateway centralizes cross-cutting concerns. Circuit breakers provide fault tolerance in distributed systems.",
    internalWorking: "Spring Cloud Gateway routes by path to downstream services. Filters handle auth, logging, rate limiting. Resilience4j circuit breaker: CLOSED→OPEN→HALF_OPEN states based on failure rate.",
    realWorldUsage: "CommerceX gateway routes /products→catalog, /orders→order-service. JWT validation at gateway. Rate limiting per API key. Circuit breaker on payment service calls.",
    codeExample: `@Bean\npublic RouteLocator routes(RouteLocatorBuilder builder) {\n    return builder.routes()\n        .route("catalog", r -> r.path("/api/v1/products/**")\n            .filters(f -> f.circuitBreaker(c -> c.setName("catalogCB")))\n            .uri("lb://catalog-service"))\n        .build();\n}`,
    productionCode: `@CircuitBreaker(name = "payment", fallbackMethod = "paymentFallback")\npublic PaymentResult charge(PaymentRequest req) {\n    return paymentClient.charge(req);\n}\npublic PaymentResult paymentFallback(PaymentRequest req, Exception e) {\n    return PaymentResult.pending(req.getId(), "Payment service unavailable");\n}`,
    bestPractices: ["Centralize auth at gateway", "Set appropriate circuit breaker thresholds", "Implement meaningful fallbacks", "Monitor circuit breaker state changes"],
    commonMistakes: ["Gateway becoming a god service with business logic", "No fallback methods", "Circuit breaker thresholds too aggressive", "Missing timeout configuration"],
    interviewQuestions: [
      { question: "Explain circuit breaker states.", answer: "CLOSED: normal operation. OPEN: failures exceeded threshold, calls fail fast. HALF_OPEN: test call allowed after wait period. Success→CLOSED, failure→OPEN. Prevents cascade failures." },
    ],
  },
  "Kafka Fundamentals": {
    overview: "Apache Kafka is a distributed event streaming platform. Producers publish to topics; consumers subscribe in consumer groups for parallel processing.",
    whyItExists: "Services need decoupled, reliable, ordered event delivery. Kafka handles millions of events/sec with durability, replay capability, and horizontal scaling.",
    internalWorking: "Topics partitioned for parallelism. Each partition ordered. Consumer groups: one consumer per partition. Offsets track read position. Replication factor ensures durability.",
    realWorldUsage: "CommerceX: order.created, inventory.reserved, payment.completed topics. FinFlow: transaction.events for audit trail. Event-driven order saga orchestration.",
    codeExample: `@Service\npublic class OrderEventPublisher {\n    private final KafkaTemplate<String, OrderCreatedEvent> kafka;\n    public void publish(Order order) {\n        kafka.send("order.created", order.getId().toString(),\n            new OrderCreatedEvent(order.getId(), order.getItems()));\n    }\n}`,
    productionCode: `@KafkaListener(topics = "order.created", groupId = "inventory-service")\npublic void reserveStock(OrderCreatedEvent event) {\n    event.getItems().forEach(item ->\n        inventoryService.reserve(item.getSku(), item.getQuantity()));\n}`,
    bestPractices: ["Use topic naming convention (domain.action)", "Key messages for partition ordering", "Design idempotent consumers", "Monitor consumer lag"],
    commonMistakes: ["Too many partitions (overhead)", "Not handling consumer rebalancing", "Missing dead letter queue", "Storing large payloads in messages"],
    interviewQuestions: [
      { question: "How does Kafka ensure ordering?", answer: "Ordering guaranteed within a partition only. Messages with same key go to same partition. Use customerId/orderId as key for per-entity ordering. Cross-partition ordering not guaranteed." },
    ],
  },
  "Event Sourcing & CQRS": {
    overview: "Event Sourcing stores state changes as immutable events. CQRS separates read models (queries) from write models (commands) for optimized access patterns.",
    whyItExists: "Traditional CRUD loses history. Event sourcing provides audit trail, temporal queries, and replay capability. CQRS optimizes read and write independently.",
    internalWorking: "Commands generate events stored in event store. Aggregate rebuilt by replaying events. Projections build read models from events. Snapshots optimize replay for long streams.",
    realWorldUsage: "FinFlow account ledger: every debit/credit is an event. Account balance computed from events. Separate read DB optimized for transaction history queries.",
    codeExample: `public class Account extends EventSourcedAggregate {\n    public void debit(Money amount) {\n        if (balance.isLessThan(amount)) throw new InsufficientFundsException();\n        apply(new AccountDebited(id, amount, Instant.now()));\n    }\n    protected void on(AccountDebited event) { balance = balance.subtract(event.amount()); }\n}`,
    productionCode: `@CommandHandler\npublic void handle(TransferCommand cmd) {\n    Account source = repository.load(cmd.getFromAccountId());\n    source.debit(cmd.getAmount());\n    Account target = repository.load(cmd.getToAccountId());\n    target.credit(cmd.getAmount());\n    repository.save(source);\n    repository.save(target);\n}`,
    bestPractices: ["Use for domains needing audit trail", "Implement snapshots for long event streams", "Version your events for schema evolution", "Separate read/write databases in CQRS"],
    commonMistakes: ["Event sourcing everything (overkill)", "Not handling event schema migration", "Missing snapshot strategy", "CQRS without clear read/write optimization need"],
    interviewQuestions: [
      { question: "When to use Event Sourcing?", answer: "When audit trail required (finance, healthcare). When temporal queries needed (state at point in time). When event-driven architecture natural. Not for simple CRUD with no history requirements." },
    ],
  },
  "Caching Patterns": {
    overview: "Caching stores frequently accessed data in fast storage (Redis, in-memory) to reduce database load and latency. Patterns: cache-aside, read-through, write-through, write-behind.",
    whyItExists: "Database queries at scale become bottlenecks. Caching reduces latency from 50ms to <1ms. Essential for product catalogs, session data, and rate limiting.",
    internalWorking: "Cache-aside: app checks cache, on miss loads DB and populates cache. TTL controls expiry. Invalidation on writes prevents stale data. Cache stampede mitigated with locking.",
    realWorldUsage: "CommerceX: product catalog cached 15min. Cart stored entirely in Redis. Session tokens with TTL. Rate limiting counters. FinFlow: fraud score cache.",
    codeExample: `public Product getProduct(String sku) {\n    String key = "product:" + sku;\n    Product cached = redis.opsForValue().get(key);\n    if (cached != null) return cached;\n    Product product = productRepo.findBySku(sku)\n        .orElseThrow(() -> new NotFoundException(sku));\n    redis.opsForValue().set(key, product, Duration.ofMinutes(15));\n    return product;\n}`,
    productionCode: `@Cacheable(value = "products", key = "#sku", unless = "#result == null")\n@CacheEvict(value = "products", key = "#product.sku")\npublic Product updateProduct(Product product) { return productRepo.save(product); }`,
    bestPractices: ["Set appropriate TTLs", "Cache invalidation on writes", "Monitor cache hit ratio", "Plan for cache failure (graceful degradation)"],
    commonMistakes: ["Caching everything without measurement", "No invalidation strategy (stale data)", "Caching null values without TTL", "Cache stampede on popular key expiry"],
    interviewQuestions: [
      { question: "Cache-aside vs read-through?", answer: "Cache-aside: app manages cache (check cache→DB→populate). Read-through: cache layer loads from DB on miss automatically. Cache-aside gives app more control; read-through simplifies app code." },
    ],
  },
  "Redis Data Structures": {
    overview: "Redis provides Strings, Hashes, Lists, Sets, Sorted Sets, Streams, and more. Each structure optimizes different access patterns beyond simple key-value.",
    whyItExists: "Different use cases need different data models. Sorted sets enable leaderboards. Streams provide lightweight messaging. Hashes store object fields efficiently.",
    internalWorking: "All structures in-memory with optional persistence (RDB/AOF). Single-threaded execution (per shard in cluster). Pub/Sub for messaging. Lua scripts for atomic operations.",
    realWorldUsage: "Strings: session tokens. Hashes: cart items. Sorted Sets: leaderboards, rate limiting windows. Streams: lightweight event log. Sets: unique visitor tracking.",
    codeExample: `// Cart as Hash\nredis.opsForHash().put("cart:" + userId, sku, quantity);\n\n// Rate limiting with Sorted Set\nredis.opsForZSet().add("rate:" + clientId, requestId, timestamp);\nredis.opsForZSet().removeRangeByScore("rate:" + clientId, 0, timestamp - 60000);`,
    productionCode: `// Sliding window rate limiter\npublic boolean isAllowed(String clientId) {\n    String key = "rate:" + clientId;\n    long now = System.currentTimeMillis();\n    redis.zRemRangeByScore(key, 0, now - WINDOW_MS);\n    if (redis.zCard(key) >= MAX_REQUESTS) return false;\n    redis.zAdd(key, now, UUID.randomUUID().toString());\n    redis.expire(key, WINDOW_MS, TimeUnit.MILLISECONDS);\n    return true;\n}`,
    bestPractices: ["Choose structure matching access pattern", "Set TTL on all keys", "Use Redis Cluster for horizontal scaling", "Monitor memory usage"],
    commonMistakes: ["Using String when Hash is more efficient", "No TTL (memory leak)", "Large values (>1MB) in Redis", "KEYS command in production"],
    interviewQuestions: [
      { question: "Redis persistence: RDB vs AOF?", answer: "RDB: point-in-time snapshots, compact, may lose recent data. AOF: logs every write, more durable, larger files. Use both for maximum durability. RDB for backups, AOF for durability." },
    ],
  },
};
