export type InterviewPriority = 1 | 2 | 3 | 4 | 5;

export interface ProgressTracking {
  status: "not_started" | "in_progress" | "completed";
  completionPercent: number;
  lastStudied?: string;
  timeSpentMinutes: number;
}

export interface Topic {
  id: string;
  title: string;
  module: string;
  interviewDefinition: string;
  distinctions: string[];
  interviewPriority: InterviewPriority;
  interviewQuestions?: { question: string; answer: string }[];
  codeExamples: { title: string; language: string; code: string }[];
  estimatedLearningTime: string;
  difficulty: Difficulty;
  prerequisites: string[];
  personalNotes: string;
  progress: ProgressTracking;
  usedInProjects: string[];
}

export interface RoadmapLevel {
  level: number;
  title: string;
  description: string;
  icon: string;
  color: string;
  xpReward: number;
  topics: Topic[];
}

export interface Roadmap {
  version: string;
  title: string;
  description: string;
  totalLevels: number;
  levels: RoadmapLevel[];
}

export interface Achievement {
  id: string;
  title: string;
  description: string;
  icon: string;
  unlocked: boolean;
  unlockedAt?: string;
  xpBonus: number;
}

export interface UserStats {
  totalXp: number;
  level: number;
  streak: number;
  longestStreak: number;
  lastActiveDate: string;
  achievements: Achievement[];
  heatmap: Record<string, number>;
  companyReadiness: {
    amazon: number;
    google: number;
    microsoft: number;
    netflix: number;
    stripe: number;
    overall: number;
  };
}

export type Difficulty = "beginner" | "intermediate" | "advanced" | "expert";

export interface Microservice {
  name: string;
  description: string;
  tech: string[];
  responsibilities: string[];
  ports: number[];
}

export interface KafkaTopic {
  name: string;
  description: string;
  producers: string[];
  consumers: string[];
  schema: string;
}

export interface ApiContract {
  service: string;
  endpoint: string;
  progress: ProgressTracking;
  usedInProjects: string[];
}

export interface RoadmapLevel {
  level: number;
  title: string;
  description: string;
  icon: string;
  color: string;
  xpReward: number;
  topics: Topic[];
}

export interface Roadmap {
  version: string;
  title: string;
  description: string;
  totalLevels: number;
  levels: RoadmapLevel[];
}

export interface Achievement {
  id: string;
  title: string;
  description: string;
  icon: string;
  unlocked: boolean;
  unlockedAt?: string;
  xpBonus: number;
}

export interface UserStats {
  totalXp: number;
  level: number;
  streak: number;
  longestStreak: number;
  lastActiveDate: string;
  achievements: Achievement[];
  heatmap: Record<string, number>;
  companyReadiness: {
    amazon: number;
    google: number;
    microsoft: number;
    netflix: number;
    stripe: number;
    overall: number;
  };
}

export interface Microservice {
  name: string;
  description: string;
  tech: string[];
  responsibilities: string[];
  ports: number[];
}

export interface KafkaTopic {
  name: string;
  description: string;
  producers: string[];
  consumers: string[];
  schema: string;
}

export interface ApiContract {
  service: string;
  endpoint: string;
  method: string;
  description: string;
  request?: string;
  response?: string;
}

export interface DatabaseTable {
  name: string;
  description: string;
  columns: {
    name: string;
    type: string;
    constraints?: string;
  }[];
  indexes?: string[];
}

export interface DatabaseColumn {
  id: string;
  name: string;
  type: string;
  nullable: boolean;
  isPrimaryKey: boolean;
  isUnique: boolean;
  defaultValue?: string;
  autoGenerated: boolean;
  description: string;
}

export type ForeignKeyAction = "CASCADE" | "SET NULL" | "RESTRICT" | "NO ACTION";

export interface DatabaseForeignKey {
  id: string;
  constraintName: string;
  column: string;
  referencedTable: string;
  referencedColumn: string;
  onDelete: ForeignKeyAction;
  onUpdate: ForeignKeyAction;
  description: string;
}

export type IndexType = "BTREE" | "HASH" | "GIN" | "GIST";

export interface DatabaseIndex {
  id: string;
  name: string;
  columns: string[];
  isUnique: boolean;
  type: IndexType;
  purpose: string;
}

export interface DetailedDatabaseTable {
  id: string;
  name: string;
  purpose: string;
  primaryKey: string;
  notes: string;
  columns: DatabaseColumn[];
  foreignKeys: DatabaseForeignKey[];
  indexes: DatabaseIndex[];
}

export interface ServiceDatabase {
  id: string;
  name: string;
  type: string;
  purpose: string;
  owningServices: string[];
  whyChosen: string;
  tables: DetailedDatabaseTable[];
}

export interface ProjectDatabaseDesign {
  databases: ServiceDatabase[];
}

export interface Milestone {
  id: string;
  title: string;
  description: string;
  order: number;
  unlockedTopics: string[];
  resumeLine: string;
  deliverables: string[];
  estimatedWeeks: number;
}

export interface Project {
  id: string;
  name: string;
  tagline: string;
  description: string;
  domain: string;
  difficulty: Difficulty;
  estimatedDuration: string;
  techStack: string[];
  microservices: Microservice[];
  folderStructure: { path: string; description: string }[];
  databases: DatabaseTable[];
  eventFlows: { name: string; steps: string[] }[];
  apiContracts: ApiContract[];
  kafkaTopics: KafkaTopic[];
  redisUsage: { key: string; pattern: string; ttl: string; purpose: string }[];
  securityArchitecture: { layer: string; implementation: string }[];
  deploymentArchitecture: { component: string; description: string }[];
  cicdPipeline: { stage: string; tools: string[]; description: string }[];
  monitoringStack: { tool: string; purpose: string; metrics: string[] }[];
  testingStrategy: { type: string; tools: string[]; coverage: string }[];
  milestones: Milestone[];
  color: string;
  icon: string;
  guide?: ProjectGuide;
}

export interface TechnologyChoice { technology: string; where: string; why: string; }
export interface NonFunctionalRequirement { area: string; target: string; rationale: string; }
export interface ProjectArchitecture { overview: string; components: { name: string; responsibility: string; technology: string[] }[]; communication: { synchronous: string[]; asynchronous: string[] }; dataOwnership: string; keyDecisions: { decision: string; reason: string; tradeOff: string }[]; }
export interface ProjectDomainEntity { name: string; purpose: string; owningService: string; persistence: string; importantFields: string[]; relationships: string[]; }
export interface ProjectDomainRelationship { from: string; to: string; type: string; description: string; }
export interface ProjectDomainModel { entities: ProjectDomainEntity[]; relationships: ProjectDomainRelationship[]; consistency: string[]; }
export type HttpMethod = "GET" | "POST" | "PUT" | "PATCH" | "DELETE";

export type ApiAuthType = "Public" | "JWT" | "Service-to-Service" | "OAuth2" | "Internal";

export type ApiCommunicationType = "SYNC REST" | "ASYNC EVENT";

export interface ApiHeader {
  id: string;
  name: string;
  value: string;
  required: boolean;
  description: string;
}

export interface ApiParameter {
  id: string;
  name: string;
  type: string;
  required: boolean;
  description: string;
  example: string;
}

export interface ApiQueryParameter {
  id: string;
  name: string;
  type: string;
  required: boolean;
  defaultValue?: string;
  description: string;
  example: string;
}

export interface ApiRequestBody {
  contentType: string;
  jsonExample: string;
  description: string;
}

export interface ApiResponseItem {
  id: string;
  statusCode: number;
  description: string;
  contentType: string;
  jsonExample: string;
}

export interface ApiErrorResponseItem {
  id: string;
  statusCode: number;
  errorCode: string;
  message: string;
  description: string;
  retryable: boolean;
  example: string;
}

export interface ApiValidationRuleItem {
  id: string;
  field: string;
  rule: string;
  value: string;
  message: string;
}

export interface ApiDependencyItem {
  id: string;
  service: string;
  communicationType: "SYNC" | "ASYNC";
  purpose: string;
  timeout: string;
  retryable: boolean;
  notes: string;
}

export interface ApiIdempotencyConfig {
  required: boolean;
  headerName: string;
  storageStrategy: string;
  conflictBehavior: string;
  ttl: string;
  notes: string;
}

export interface ApiPaginationConfig {
  enabled: boolean;
  pageParam: string;
  sizeParam: string;
  sortParam: string;
  defaultSize: number;
  maxSize: number;
  exampleResponse?: string;
}

export interface DetailedApiContract {
  id: string;
  service: string;
  module: string;
  method: HttpMethod;
  path: string;
  purpose: string;
  description: string;
  authentication: ApiAuthType;
  authorization: string[];
  idempotency: ApiIdempotencyConfig;
  requestHeaders: ApiHeader[];
  pathParameters: ApiParameter[];
  queryParameters: ApiQueryParameter[];
  requestBody: ApiRequestBody;
  responses: ApiResponseItem[];
  errorResponses: ApiErrorResponseItem[];
  validationRules: ApiValidationRuleItem[];
  pagination: ApiPaginationConfig;
  downstreamDependencies: ApiDependencyItem[];
  communicationType: ApiCommunicationType;
  version: string;
  notes: string;
}

export interface ProjectApiContracts {
  contracts: DetailedApiContract[];
}

export interface ServiceImplementationStep {
  id: string;
  order: number;
  title: string;
  description: string;
}

export interface ServicePackageItem {
  id: string;
  path: string;
  purpose: string;
}

export interface ServiceMavenDependency {
  id: string;
  name: string;
  purpose: string;
  required: boolean;
  version?: string;
  notes?: string;
}

export interface ServiceDtoItem {
  id: string;
  name: string;
  purpose: string;
  fields: { name: string; type: string; validation: string; description: string }[];
  api: string;
}

export interface ServiceControllerGuide {
  id: string;
  apiEndpoint: string;
  method: string;
  responsibility: string[];
  javaCode: string;
}

export interface ServiceLayerGuideItem {
  id: string;
  operation: string;
  transactionBoundary: string;
  javaCode: string;
  explanation: string;
}

export interface ServiceRepositoryGuide {
  id: string;
  name: string;
  interfaceCode: string;
  queryPurpose: string;
  indexReq: string;
  notes: string;
}

export interface ServiceExceptionItem {
  id: string;
  exceptionName: string;
  type: string;
  statusCode: number;
  handlerCode: string;
}

export interface ServiceEventGuideItem {
  id: string;
  eventName: string;
  role: "PRODUCER" | "CONSUMER";
  payload: string;
  purpose: string;
  ordering: string;
  idempotency: string;
  javaModelCode: string;
}

export interface ServiceTestingGuideItem {
  id: string;
  testType: string;
  tools: string[];
  target: string;
  javaCode: string;
}

export interface ServiceFailureScenarioItem {
  id: string;
  scenario: string;
  problem: string;
  detection: string;
  handling: string;
  recovery: string;
  consistency: string;
}

export interface ServiceChecklistItem {
  id: string;
  label: string;
  completed: boolean;
}

export interface ServiceCodeWorkspaceFile {
  id: string;
  title: string;
  language: string;
  filename: string;
  code: string;
}

export interface DetailedServiceGuide {
  id: string;
  serviceName: string;
  responsibility: string;
  businessPurpose: string;
  ownedEntities: string[];
  ownedDatabase: string;
  exposedApis: string[];
  consumedApis: string[];
  publishedEvents: string[];
  consumedEvents: string[];
  redisUsage: string;
  externalDependencies: string[];
  technologyChoices: string[];
  keyDesignDecisions: string[];
  notes: string;
  implementationSteps: ServiceImplementationStep[];
  packageStructure: ServicePackageItem[];
  mavenDependencies: ServiceMavenDependency[];
  configurationYml: string;
  dtos: ServiceDtoItem[];
  controllerGuides: ServiceControllerGuide[];
  serviceLayerGuides: ServiceLayerGuideItem[];
  repositoryGuides: ServiceRepositoryGuide[];
  exceptionHandlers: ServiceExceptionItem[];
  transactionDesign: {
    boundary: string;
    isolation: string;
    propagation: string;
    rollback: string;
    concurrencyControl: string;
    notes: string;
  };
  eventsGuides: ServiceEventGuideItem[];
  testingGuides: ServiceTestingGuideItem[];
  failureScenarios: ServiceFailureScenarioItem[];
  checklist: ServiceChecklistItem[];
  codeWorkspace: ServiceCodeWorkspaceFile[];
}

export interface ProjectTechCard {
  category: "Backend" | "Database" | "Messaging" | "Caching" | "Security" | "Containerization" | "Cloud" | "Observability" | "Testing" | "CI/CD";
  technology: string;
  where: string;
  why: string;
}

export interface ProjectServiceSpec {
  id: string;
  name: string;
  purpose: string;
  responsibilities: string[];
  ownedEntities: string[];
  database: string;
  apis: string[];
  publishedEvents: string[];
  consumedEvents: string[];
  dependencies: string[];
  designConcerns: string[];
}

export interface ProjectApiSpec {
  id: string;
  method: HttpMethod;
  path: string;
  purpose: string;
  owner: string;
  authentication: string;
  requestFields: string[];
  response: string;
  importantErrors: string[];
  idempotencyRequired: boolean;
  pagination: boolean;
  downstreamDependencies: string[];
}

export interface ProjectEventSpec {
  id: string;
  name: string;
  producer: string;
  consumers: string[];
  purpose: string;
  payloadFields: string[];
  partitionKey: string;
  deliveryExpectations: string;
  businessImpact: string;
}

export interface SecurityReliabilityRequirement {
  id: string;
  category: string;
  requirement: string;
  rationale: string;
}

export interface BuildPlanPhase {
  id: string;
  phaseNumber: number;
  title: string;
  description: string;
  tasks: string[];
  dependencies?: string[];
}

export interface ProjectInterviewPrompt {
  id: string;
  topic: string;
  question: string;
  discussionPoints: string[];
}

export interface ProjectGuideOverview {
  projectName: string;
  shortDescription: string;
  goal: string;
  businessProblem: string;
  whyItExists: string;
  learningOutcomes: string[];
  targetExperience: string;
  expectedOutcome: string;
}

export interface ProjectServiceGuides {
  services: DetailedServiceGuide[];
}

export interface ProjectGuide {
  _seedVersion?: number;
  overview?: string[];
  overviewSpec?: ProjectGuideOverview;
  businessRequirements?: string[];
  functionalRequirements?: { domain: string; requirements: string[] }[];
  nonFunctionalRequirements?: NonFunctionalRequirement[];
  technologyChoices?: TechnologyChoice[];
  techStackCards?: ProjectTechCard[];
  architecture?: ProjectArchitecture;
  architectureSpec?: {
    overview: string;
    components: { name: string; responsibility: string; why: string; technology: string[] }[];
    communication: { synchronous: string[]; asynchronous: string[] };
    dataOwnership: string;
    keyDecisions: { decision: string; reason: string; tradeOff: string }[];
  };
  domainModel?: ProjectDomainModel;
  serviceSpecs?: ProjectServiceSpec[];
  databaseDesign?: ProjectDatabaseDesign;
  apiContractsDesign?: ProjectApiContracts;
  apiSpecs?: ProjectApiSpec[];
  eventSpecs?: ProjectEventSpec[];
  securityRequirements?: SecurityReliabilityRequirement[];
  reliabilityRequirements?: SecurityReliabilityRequirement[];
  observabilityRequirements?: SecurityReliabilityRequirement[];
  buildPlanPhases?: BuildPlanPhase[];
  interviewDiscussion?: {
    elevatorPitch: string;
    architectureExplanation: string;
    prompts: ProjectInterviewPrompt[];
  };
  serviceGuidesDesign?: ProjectServiceGuides;
}

export interface SkillProjectMapping {
  topicId: string;
  topicTitle: string;
  level: number;
  projects: {
    projectId: string;
    projectName: string;
    implementation: string;
    files: string[];
    phase: string;
  }[];
}

export interface BuildOrderStep {
  order: number;
  projectId: string;
  milestoneId: string;
  title: string;
  description: string;
  topicIds: string[];
  teamPhase: string;
  dependencies: number[];
}

// ============================================================================
// INTERVIEW QUESTION BANK MODELS (COMPANY → QUESTION SET → QUESTIONS)
// ============================================================================
export interface Company {
  id: string;
  name: string;
  description?: string;
  logoUrl?: string;
  createdAt: string;
  updatedAt: string;
}

export interface QuestionSet {
  id: string;
  companyId: string;
  title: string;
  role?: string;
  experience?: string;
  interviewRound?: string;
  source?: string;
  sourceUrl?: string;
  notes?: string;
  rawContent?: string;
  createdAt: string;
  updatedAt: string;
}

export interface InterviewQuestion {
  id: string;
  questionSetId: string; // Primary mapping
  topicId?: string; // Legacy fallback mapping
  question: string;
  answer?: string;
  order: number;
  tags?: string[];
  difficulty?: "Easy" | "Medium" | "Hard";
  company?: string; // Legacy fallback
  referenceUrl?: string;
  createdAt: string;
  updatedAt: string;
}

export type QuestionSetViewMode = "read" | "edit" | "raw";

// Legacy Topic interface kept for migration compatibility
export interface InterviewTopic {
  id: string;
  name: string;
  description?: string;
  order: number;
}

// ============================================================================
// PERSONAL RESOURCES LIBRARY MODELS
// ============================================================================
export type ResourceType = "Link" | "PDF" | "Document" | "Spreadsheet" | "Presentation" | "Image" | "Other";

export interface ResourceCategory {
  id: string;
  name: string;
  order: number;
}

export interface ResourceItem {
  id: string;
  title: string;
  description?: string;
  type: ResourceType;
  categoryId: string;
  tags: string[];
  notes?: string;
  url?: string;
  fileName?: string;
  mimeType?: string;
  fileSize?: number;
  storedFileId?: string;
  isFavorite?: boolean;
  createdAt: string;
  updatedAt: string;
}

// ============================================================================
// ENGINEERING LAB MODELS
// ============================================================================
export interface EngineeringLabModule {
  name: string;
  purpose: string;
  responsibilities: string[];
  designConcerns: string[];
}

export interface EngineeringLabChallenge {
  challenge: string;
  expectedDesignConcern: string;
  mitigationStrategy: string;
}

export interface EngineeringLabBuildPhase {
  phaseNumber: number;
  title: string;
  goal: string;
  whatToBuild: string[];
  engineeringDecision: string;
  expectedOutcome: string;
}

export interface EngineeringLab {
  id: string;
  title: string;
  shortDescription: string;
  problemStatement: string;
  interviewRelevance: string;
  relevanceRating?: number;
  difficulty: "Intermediate" | "Advanced" | "Expert";
  estimatedScope: string;
  primarySkills: string[];
  overview: string;
  requirements: {
    business: string[];
    functional: string[];
    nonFunctional: string[];
  };
  technologies: {
    category: string;
    technology: string;
    where?: string;
    why: string;
  }[];
  architecture: {
    overview: string;
    components: { name: string; responsibility: string; why: string }[];
    communication: string[];
    keyDecisions: { decision: string; reason: string; tradeOff: string }[];
  };
  modules: EngineeringLabModule[];
  dataDesign: {
    databases: {
      name: string;
      type: string;
      purpose: string;
      tables: {
        name: string;
        purpose: string;
        primaryKey: string;
        columns: string[];
        indexes: string[];
      }[];
    }[];
  };
  apiDesign: {
    apis: {
      method: string;
      path: string;
      purpose: string;
      requestFields: string[];
      response: string | string[];
      errors: string[];
    }[];
  };
  eventDesign: {
    events: {
      name: string;
      producer: string;
      consumers: string[];
      payload: string[];
      impact: string;
    }[];
  };
  securityReliability: {
    security: string[];
    reliability: string[];
    observability: string[];
  };
  engineeringChallenges: EngineeringLabChallenge[];
  buildPlan: EngineeringLabBuildPhase[];
  interviewDiscussion: {
    elevatorPitch: string;
    prompts: {
      topic: string;
      question: string;
      discussionPoints: string[];
    }[];
  };
  _seedVersion?: number;
  isCustom?: boolean;
}


