import type { Project, ProjectDatabaseDesign, ServiceDatabase, DetailedDatabaseTable } from "@/types";

export function getSeedDatabaseDesign(project: Project): ProjectDatabaseDesign {
  if (project.id === "commercex") {
    return {
      databases: commercexSeedDatabases,
    };
  }
  if (project.id === "finflow") {
    return {
      databases: finflowSeedDatabases,
    };
  }
  if (project.id === "logistics") {
    return {
      databases: logisticsSeedDatabases,
    };
  }

  // Fallback for non-CommerceX projects
  const fallbackDatabase: ServiceDatabase = {
    id: `${project.id}-db`,
    name: `${project.name} Relational Database`,
    type: "PostgreSQL",
    purpose: "Primary transactional data store for project entities.",
    owningServices: project.microservices.slice(0, 2).map((s) => s.name),
    whyChosen: "Standard ACID relational store suitable for core application domain.",
    tables: project.databases.map((dbTable) => {
      const primaryKeyCol = dbTable.columns.find((c) => c.constraints?.toUpperCase().includes("PRIMARY KEY"));
      const pkName = primaryKeyCol ? primaryKeyCol.name : "id";

      return {
        id: dbTable.name,
        name: dbTable.name,
        purpose: dbTable.description || `Stores ${dbTable.name} records`,
        primaryKey: pkName,
        notes: "Seed table imported from project specifications.",
        columns: dbTable.columns.map((c, i) => {
          const isPk = c.constraints?.toUpperCase().includes("PRIMARY KEY") ?? false;
          const isUnq = c.constraints?.toUpperCase().includes("UNIQUE") ?? false;
          const isNotNull = c.constraints?.toUpperCase().includes("NOT NULL") ?? isPk;

          return {
            id: `col-${i}-${c.name}`,
            name: c.name,
            type: c.type,
            nullable: !isNotNull,
            isPrimaryKey: isPk,
            isUnique: isUnq,
            autoGenerated: isPk && c.type.toUpperCase() === "UUID",
            defaultValue: isPk && c.type.toUpperCase() === "UUID" ? "gen_random_uuid()" : undefined,
            description: `${c.name} field`,
          };
        }),
        foreignKeys: [],
        indexes: (dbTable.indexes || []).map((idxName, i) => ({
          id: `idx-${i}-${idxName}`,
          name: idxName,
          columns: [dbTable.columns.find((col) => idxName.includes(col.name))?.name || dbTable.columns[0]?.name || "id"],
          isUnique: idxName.toLowerCase().includes("unique"),
          type: "BTREE",
          purpose: `Performance index for ${idxName}`,
        })),
      };
    }),
  };

  return {
    databases: [fallbackDatabase],
  };
}

const commercexSeedDatabases: ServiceDatabase[] = [
  {
    id: "auth-db",
    name: "Auth Service DB",
    type: "PostgreSQL",
    purpose: "Owns customer identity, credentials, and authorization status.",
    owningServices: ["user-service", "auth-service"],
    whyChosen: "Requires ACID guarantees, strong unique constraints for email, and reliable indexing.",
    tables: [
      {
        id: "tbl-customer",
        name: "customer",
        purpose: "Stores registered customer account profiles and security status.",
        primaryKey: "id",
        notes: "Identity source of truth. Referenced across microservices by customerId without cross-service foreign keys.",
        columns: [
          { id: "c1", name: "id", type: "UUID", nullable: false, isPrimaryKey: true, isUnique: true, autoGenerated: true, defaultValue: "gen_random_uuid()", description: "Unique customer identifier" },
          { id: "c2", name: "email", type: "VARCHAR(255)", nullable: false, isPrimaryKey: false, isUnique: true, autoGenerated: false, description: "Customer login email address" },
          { id: "c3", name: "display_name", type: "VARCHAR(100)", nullable: false, isPrimaryKey: false, isUnique: false, autoGenerated: false, description: "Full display name" },
          { id: "c4", name: "password_hash", type: "VARCHAR(255)", nullable: false, isPrimaryKey: false, isUnique: false, autoGenerated: false, description: "Bcrypt or Argon2 salted credential hash" },
          { id: "c5", name: "status", type: "VARCHAR(20)", nullable: false, isPrimaryKey: false, isUnique: false, autoGenerated: false, defaultValue: "'ACTIVE'", description: "Account state (ACTIVE, SUSPENDED, PENDING_VERIFICATION)" },
          { id: "c6", name: "created_at", type: "TIMESTAMP", nullable: false, isPrimaryKey: false, isUnique: false, autoGenerated: true, defaultValue: "CURRENT_TIMESTAMP", description: "Profile creation timestamp" },
          { id: "c7", name: "updated_at", type: "TIMESTAMP", nullable: false, isPrimaryKey: false, isUnique: false, autoGenerated: true, defaultValue: "CURRENT_TIMESTAMP", description: "Profile last modification timestamp" },
        ],
        foreignKeys: [],
        indexes: [
          { id: "i1", name: "idx_customer_email", columns: ["email"], isUnique: true, type: "BTREE", purpose: "Fast lookup and uniqueness enforcement for customer authentication" },
          { id: "i2", name: "idx_customer_status", columns: ["status"], isUnique: false, type: "BTREE", purpose: "Filtering active vs suspended user accounts" },
        ],
      },
    ],
  },
  {
    id: "catalog-db",
    name: "Catalog Service DB",
    type: "PostgreSQL",
    purpose: "Stores sellable products, pricing, and category taxonomy.",
    owningServices: ["catalog-service"],
    whyChosen: "Relational foreign keys support category hierarchies; read-heavy load cached by Redis.",
    tables: [
      {
        id: "tbl-category",
        name: "category",
        purpose: "Taxonomy categories for product discovery.",
        primaryKey: "id",
        notes: "Supports multi-level category trees via self-referencing parent_category_id.",
        columns: [
          { id: "cat1", name: "id", type: "UUID", nullable: false, isPrimaryKey: true, isUnique: true, autoGenerated: true, defaultValue: "gen_random_uuid()", description: "Category primary key" },
          { id: "cat2", name: "name", type: "VARCHAR(100)", nullable: false, isPrimaryKey: false, isUnique: false, autoGenerated: false, description: "Category display title" },
          { id: "cat3", name: "slug", type: "VARCHAR(100)", nullable: false, isPrimaryKey: false, isUnique: true, autoGenerated: false, description: "SEO URL slug" },
          { id: "cat4", name: "parent_category_id", type: "UUID", nullable: true, isPrimaryKey: false, isUnique: false, autoGenerated: false, description: "Parent category for nesting" },
          { id: "cat5", name: "status", type: "VARCHAR(20)", nullable: false, isPrimaryKey: false, isUnique: false, autoGenerated: false, defaultValue: "'ACTIVE'", description: "Category status" },
        ],
        foreignKeys: [
          { id: "fk1", constraintName: "fk_category_parent", column: "parent_category_id", referencedTable: "category", referencedColumn: "id", onDelete: "SET NULL", onUpdate: "CASCADE", description: "Hierarchical parent category self-reference" },
        ],
        indexes: [
          { id: "cat_idx1", name: "idx_category_slug", columns: ["slug"], isUnique: true, type: "BTREE", purpose: "Fast category lookup by URL slug" },
          { id: "cat_idx2", name: "idx_category_parent", columns: ["parent_category_id"], isUnique: false, type: "BTREE", purpose: "Fetching child categories" },
        ],
      },
      {
        id: "tbl-product",
        name: "product",
        purpose: "Sellable product items with SKU and pricing.",
        primaryKey: "id",
        notes: "Catalog items retain stable SKUs; changes publish events to update search indices.",
        columns: [
          { id: "p1", name: "id", type: "UUID", nullable: false, isPrimaryKey: true, isUnique: true, autoGenerated: true, defaultValue: "gen_random_uuid()", description: "Product primary key" },
          { id: "p2", name: "sku", type: "VARCHAR(64)", nullable: false, isPrimaryKey: false, isUnique: true, autoGenerated: false, description: "Stock keeping unit code" },
          { id: "p3", name: "name", type: "VARCHAR(255)", nullable: false, isPrimaryKey: false, isUnique: false, autoGenerated: false, description: "Product name" },
          { id: "p4", name: "description", type: "TEXT", nullable: true, isPrimaryKey: false, isUnique: false, autoGenerated: false, description: "Full product text description" },
          { id: "p5", name: "price", type: "DECIMAL(10,2)", nullable: false, isPrimaryKey: false, isUnique: false, autoGenerated: false, description: "Current unit price" },
          { id: "p6", name: "currency", type: "VARCHAR(3)", nullable: false, isPrimaryKey: false, isUnique: false, autoGenerated: false, defaultValue: "'USD'", description: "ISO currency code" },
          { id: "p7", name: "category_id", type: "UUID", nullable: false, isPrimaryKey: false, isUnique: false, autoGenerated: false, description: "Owning category ID" },
          { id: "p8", name: "status", type: "VARCHAR(20)", nullable: false, isPrimaryKey: false, isUnique: false, autoGenerated: false, defaultValue: "'PUBLISHED'", description: "DRAFT, PUBLISHED, ARCHIVED" },
          { id: "p9", name: "created_at", type: "TIMESTAMP", nullable: false, isPrimaryKey: false, isUnique: false, autoGenerated: true, defaultValue: "CURRENT_TIMESTAMP", description: "Catalog entry creation timestamp" },
        ],
        foreignKeys: [
          { id: "fk2", constraintName: "fk_product_category", column: "category_id", referencedTable: "category", referencedColumn: "id", onDelete: "RESTRICT", onUpdate: "CASCADE", description: "Enforces category assignment within Catalog Service DB" },
        ],
        indexes: [
          { id: "p_idx1", name: "idx_product_sku", columns: ["sku"], isUnique: true, type: "BTREE", purpose: "Fast SKU lookup" },
          { id: "p_idx2", name: "idx_product_category_status", columns: ["category_id", "status"], isUnique: false, type: "BTREE", purpose: "Filtering published products by category" },
        ],
      },
    ],
  },
  {
    id: "cart-db",
    name: "Cart Service Cache & Store",
    type: "Redis & Relational Backup",
    purpose: "Maintains temporary, high-throughput customer shopping carts.",
    owningServices: ["cart-service"],
    whyChosen: "Redis key-value store provides sub-millisecond cart reads and TTL expiry.",
    tables: [
      {
        id: "tbl-cart",
        name: "cart",
        purpose: "Shopping cart header per active customer.",
        primaryKey: "id",
        notes: "Keyed by customer_id for direct session retrieval.",
        columns: [
          { id: "crt1", name: "id", type: "UUID", nullable: false, isPrimaryKey: true, isUnique: true, autoGenerated: true, defaultValue: "gen_random_uuid()", description: "Cart session ID" },
          { id: "crt2", name: "customer_id", type: "UUID", nullable: false, isPrimaryKey: false, isUnique: true, autoGenerated: false, description: "Customer owner ID" },
          { id: "crt3", name: "updated_at", type: "TIMESTAMP", nullable: false, isPrimaryKey: false, isUnique: false, autoGenerated: true, defaultValue: "CURRENT_TIMESTAMP", description: "Last modified timestamp" },
          { id: "crt4", name: "expires_at", type: "TIMESTAMP", nullable: false, isPrimaryKey: false, isUnique: false, autoGenerated: false, description: "Cart TTL expiry deadline" },
        ],
        foreignKeys: [],
        indexes: [
          { id: "crt_idx1", name: "idx_cart_customer", columns: ["customer_id"], isUnique: true, type: "BTREE", purpose: "Unique active cart per customer" },
        ],
      },
      {
        id: "tbl-cart-item",
        name: "cart_item",
        purpose: "Individual line item in an active cart.",
        primaryKey: "cart_id",
        notes: "Product details are snapshot references to prevent cross-service joins.",
        columns: [
          { id: "ci1", name: "cart_id", type: "UUID", nullable: false, isPrimaryKey: true, isUnique: false, autoGenerated: false, description: "Owning cart ID" },
          { id: "ci2", name: "product_id", type: "UUID", nullable: false, isPrimaryKey: true, isUnique: false, autoGenerated: false, description: "Catalog Product ID reference" },
          { id: "ci3", name: "quantity", type: "INTEGER", nullable: false, isPrimaryKey: false, isUnique: false, autoGenerated: false, defaultValue: "1", description: "Item quantity selected" },
          { id: "ci4", name: "unit_price", type: "DECIMAL(10,2)", nullable: false, isPrimaryKey: false, isUnique: false, autoGenerated: false, description: "Price snapshot" },
        ],
        foreignKeys: [
          { id: "fk3", constraintName: "fk_cart_item_cart", column: "cart_id", referencedTable: "cart", referencedColumn: "id", onDelete: "CASCADE", onUpdate: "CASCADE", description: "Deletes items when cart expires or clears" },
        ],
        indexes: [],
      },
    ],
  },
  {
    id: "inventory-db",
    name: "Inventory Service DB",
    type: "PostgreSQL",
    purpose: "Manages physical stock quantities, optimistic locking, and checkout reservations.",
    owningServices: ["inventory-service"],
    whyChosen: "Transactional isolation and row-level locking prevent overselling under high concurrency.",
    tables: [
      {
        id: "tbl-inventory",
        name: "inventory",
        purpose: "Physical stock levels per product with version control.",
        primaryKey: "product_id",
        notes: "Uses integer version for optimistic locking (`UPDATE inventory SET available = available - q, version = version + 1 WHERE product_id = ? AND version = ?`).",
        columns: [
          { id: "inv1", name: "product_id", type: "UUID", nullable: false, isPrimaryKey: true, isUnique: true, autoGenerated: false, description: "Catalog Product ID reference" },
          { id: "inv2", name: "available_quantity", type: "INTEGER", nullable: false, isPrimaryKey: false, isUnique: false, autoGenerated: false, defaultValue: "0", description: "Unreserved sellable stock" },
          { id: "inv3", name: "reserved_quantity", type: "INTEGER", nullable: false, isPrimaryKey: false, isUnique: false, autoGenerated: false, defaultValue: "0", description: "Stock held for pending checkouts" },
          { id: "inv4", name: "version", type: "BIGINT", nullable: false, isPrimaryKey: false, isUnique: false, autoGenerated: false, defaultValue: "0", description: "Optimistic concurrency control version" },
          { id: "inv5", name: "updated_at", type: "TIMESTAMP", nullable: false, isPrimaryKey: false, isUnique: false, autoGenerated: true, defaultValue: "CURRENT_TIMESTAMP", description: "Stock update timestamp" },
        ],
        foreignKeys: [],
        indexes: [
          { id: "inv_idx1", name: "idx_inventory_available", columns: ["available_quantity"], isUnique: false, type: "BTREE", purpose: "Identify low stock products for automated replenishment" },
        ],
      },
      {
        id: "tbl-inventory-reservation",
        name: "inventory_reservation",
        purpose: "Expiring stock reservation holds created during checkout.",
        primaryKey: "id",
        notes: "Background worker releases expired reservations back into available stock.",
        columns: [
          { id: "res1", name: "id", type: "UUID", nullable: false, isPrimaryKey: true, isUnique: true, autoGenerated: true, defaultValue: "gen_random_uuid()", description: "Reservation ID" },
          { id: "res2", name: "order_id", type: "UUID", nullable: false, isPrimaryKey: false, isUnique: false, autoGenerated: false, description: "Associated order ID" },
          { id: "res3", name: "product_id", type: "UUID", nullable: false, isPrimaryKey: false, isUnique: false, autoGenerated: false, description: "Reserved product ID" },
          { id: "res4", name: "quantity", type: "INTEGER", nullable: false, isPrimaryKey: false, isUnique: false, autoGenerated: false, description: "Quantity on hold" },
          { id: "res5", name: "status", type: "VARCHAR(20)", nullable: false, isPrimaryKey: false, isUnique: false, autoGenerated: false, defaultValue: "'PENDING'", description: "PENDING, CONFIRMED, EXPIRED, RELEASED" },
          { id: "res6", name: "expires_at", type: "TIMESTAMP", nullable: false, isPrimaryKey: false, isUnique: false, autoGenerated: false, description: "Hold expiration deadline" },
          { id: "res7", name: "created_at", type: "TIMESTAMP", nullable: false, isPrimaryKey: false, isUnique: false, autoGenerated: true, defaultValue: "CURRENT_TIMESTAMP", description: "Hold timestamp" },
        ],
        foreignKeys: [],
        indexes: [
          { id: "res_idx1", name: "idx_reservation_order", columns: ["order_id"], isUnique: false, type: "BTREE", purpose: "Lookup reservations by order" },
          { id: "res_idx2", name: "idx_reservation_status_expiry", columns: ["status", "expires_at"], isUnique: false, type: "BTREE", purpose: "Sweeper query for releasing expired reservations" },
        ],
      },
    ],
  },
  {
    id: "order-db",
    name: "Order Service DB",
    type: "PostgreSQL",
    purpose: "Owns customer order lifecycle, order items, and saga status.",
    owningServices: ["order-service"],
    whyChosen: "Requires strict transactional durability for financials and purchase history.",
    tables: [
      {
        id: "tbl-orders",
        name: "orders",
        purpose: "Primary order header record.",
        primaryKey: "id",
        notes: "Idempotency key prevents duplicate orders on network retries.",
        columns: [
          { id: "o1", name: "id", type: "UUID", nullable: false, isPrimaryKey: true, isUnique: true, autoGenerated: true, defaultValue: "gen_random_uuid()", description: "Order unique primary key" },
          { id: "o2", name: "customer_id", type: "UUID", nullable: false, isPrimaryKey: false, isUnique: false, autoGenerated: false, description: "Customer owner ID" },
          { id: "o3", name: "status", type: "VARCHAR(50)", nullable: false, isPrimaryKey: false, isUnique: false, autoGenerated: false, defaultValue: "'CREATED'", description: "CREATED, RESERVED, PAID, COMPLETED, CANCELLED" },
          { id: "o4", name: "total_amount", type: "DECIMAL(12,2)", nullable: false, isPrimaryKey: false, isUnique: false, autoGenerated: false, description: "Calculated grand total" },
          { id: "o5", name: "currency", type: "VARCHAR(3)", nullable: false, isPrimaryKey: false, isUnique: false, autoGenerated: false, defaultValue: "'USD'", description: "ISO currency code" },
          { id: "o6", name: "idempotency_key", type: "VARCHAR(128)", nullable: false, isPrimaryKey: false, isUnique: true, autoGenerated: false, description: "Client idempotency token" },
          { id: "o7", name: "created_at", type: "TIMESTAMP", nullable: false, isPrimaryKey: false, isUnique: false, autoGenerated: true, defaultValue: "CURRENT_TIMESTAMP", description: "Order timestamp" },
        ],
        foreignKeys: [],
        indexes: [
          { id: "o_idx1", name: "idx_orders_customer_status", columns: ["customer_id", "status"], isUnique: false, type: "BTREE", purpose: "Efficient customer order history query" },
          { id: "o_idx2", name: "idx_orders_idempotency", columns: ["idempotency_key"], isUnique: true, type: "BTREE", purpose: "Enforce single order per idempotency key" },
        ],
      },
      {
        id: "tbl-order-item",
        name: "order_item",
        purpose: "Immutable product snapshot line item at time of purchase.",
        primaryKey: "id",
        notes: "Stores historic SKU and unit_price so subsequent catalog edits do not affect past orders.",
        columns: [
          { id: "oi1", name: "id", type: "UUID", nullable: false, isPrimaryKey: true, isUnique: true, autoGenerated: true, defaultValue: "gen_random_uuid()", description: "Line item primary key" },
          { id: "oi2", name: "order_id", type: "UUID", nullable: false, isPrimaryKey: false, isUnique: false, autoGenerated: false, description: "Owning order ID" },
          { id: "oi3", name: "product_id", type: "UUID", nullable: false, isPrimaryKey: false, isUnique: false, autoGenerated: false, description: "Catalog product reference" },
          { id: "oi4", name: "sku", type: "VARCHAR(64)", nullable: false, isPrimaryKey: false, isUnique: false, autoGenerated: false, description: "Snapshot SKU" },
          { id: "oi5", name: "quantity", type: "INTEGER", nullable: false, isPrimaryKey: false, isUnique: false, autoGenerated: false, description: "Quantity purchased" },
          { id: "oi6", name: "unit_price", type: "DECIMAL(10,2)", nullable: false, isPrimaryKey: false, isUnique: false, autoGenerated: false, description: "Price snapshot" },
        ],
        foreignKeys: [
          { id: "fk4", constraintName: "fk_order_item_order", column: "order_id", referencedTable: "orders", referencedColumn: "id", onDelete: "CASCADE", onUpdate: "CASCADE", description: "Binds line items to parent order" },
        ],
        indexes: [
          { id: "oi_idx1", name: "idx_order_item_order", columns: ["order_id"], isUnique: false, type: "BTREE", purpose: "Fetch all items for an order" },
        ],
      },
    ],
  },
  {
    id: "payment-db",
    name: "Payment Service DB",
    type: "PostgreSQL",
    purpose: "Records payment attempts, gateway transactions, and provider references.",
    owningServices: ["payment-service"],
    whyChosen: "Strict ACID compliance and unique idempotency keys eliminate duplicate billing.",
    tables: [
      {
        id: "tbl-payment",
        name: "payment",
        purpose: "Payment transaction attempt and provider reference.",
        primaryKey: "id",
        notes: "Receives payment events from payment gateways (Stripe/PayPal).",
        columns: [
          { id: "pay1", name: "id", type: "UUID", nullable: false, isPrimaryKey: true, isUnique: true, autoGenerated: true, defaultValue: "gen_random_uuid()", description: "Payment record ID" },
          { id: "pay2", name: "order_id", type: "UUID", nullable: false, isPrimaryKey: false, isUnique: false, autoGenerated: false, description: "Associated order ID" },
          { id: "pay3", name: "amount", type: "DECIMAL(12,2)", nullable: false, isPrimaryKey: false, isUnique: false, autoGenerated: false, description: "Charged amount" },
          { id: "pay4", name: "status", type: "VARCHAR(30)", nullable: false, isPrimaryKey: false, isUnique: false, autoGenerated: false, defaultValue: "'INITIATED'", description: "INITIATED, SUCCESS, FAILED, REFUNDED" },
          { id: "pay5", name: "provider_reference", type: "VARCHAR(255)", nullable: true, isPrimaryKey: false, isUnique: false, autoGenerated: false, description: "External gateway transaction ID" },
          { id: "pay6", name: "idempotency_key", type: "VARCHAR(128)", nullable: false, isPrimaryKey: false, isUnique: true, autoGenerated: false, description: "Deduplication key for charging" },
          { id: "pay7", name: "created_at", type: "TIMESTAMP", nullable: false, isPrimaryKey: false, isUnique: false, autoGenerated: true, defaultValue: "CURRENT_TIMESTAMP", description: "Transaction timestamp" },
        ],
        foreignKeys: [],
        indexes: [
          { id: "pay_idx1", name: "idx_payment_order", columns: ["order_id"], isUnique: false, type: "BTREE", purpose: "Lookup payment by order" },
          { id: "pay_idx2", name: "idx_payment_idempotency", columns: ["idempotency_key"], isUnique: true, type: "BTREE", purpose: "Idempotent payment processing" },
        ],
      },
    ],
  },
  {
    id: "fulfillment-db",
    name: "Fulfillment & Shipping DB",
    type: "PostgreSQL",
    purpose: "Manages package fulfillment, carrier selection, and tracking status.",
    owningServices: ["shipping-service", "fulfillment-service"],
    whyChosen: "Transactional updates linked with Kafka events for status tracking.",
    tables: [
      {
        id: "tbl-shipment",
        name: "shipment",
        purpose: "Fulfillment package record and tracking code.",
        primaryKey: "id",
        notes: "Updated upon receiving carrier webhooks or dispatch events.",
        columns: [
          { id: "shp1", name: "id", type: "UUID", nullable: false, isPrimaryKey: true, isUnique: true, autoGenerated: true, defaultValue: "gen_random_uuid()", description: "Shipment ID" },
          { id: "shp2", name: "order_id", type: "UUID", nullable: false, isPrimaryKey: false, isUnique: false, autoGenerated: false, description: "Associated order ID" },
          { id: "shp3", name: "carrier", type: "VARCHAR(50)", nullable: false, isPrimaryKey: false, isUnique: false, autoGenerated: false, description: "FedEx, UPS, DHL" },
          { id: "shp4", name: "tracking_number", type: "VARCHAR(100)", nullable: true, isPrimaryKey: false, isUnique: false, autoGenerated: false, description: "Carrier tracking code" },
          { id: "shp5", name: "status", type: "VARCHAR(30)", nullable: false, isPrimaryKey: false, isUnique: false, autoGenerated: false, defaultValue: "'PENDING'", description: "PENDING, DISPATCHED, DELIVERED" },
          { id: "shp6", name: "shipped_at", type: "TIMESTAMP", nullable: true, isPrimaryKey: false, isUnique: false, autoGenerated: false, description: "Dispatch timestamp" },
        ],
        foreignKeys: [],
        indexes: [
          { id: "shp_idx1", name: "idx_shipment_order", columns: ["order_id"], isUnique: false, type: "BTREE", purpose: "Lookup shipment by order" },
        ],
      },
    ],
  },
  {
    id: "notification-db",
    name: "Notification Service DB",
    type: "PostgreSQL",
    purpose: "Audits customer notifications and prevents duplicate event delivery.",
    owningServices: ["notification-service"],
    whyChosen: "Tracks dispatched email/SMS events to guarantee at-least-once processing without spamming users.",
    tables: [
      {
        id: "tbl-notification",
        name: "notification",
        purpose: "Customer notification delivery audit log.",
        primaryKey: "id",
        notes: "Event ID index avoids duplicate sends from Kafka re-deliveries.",
        columns: [
          { id: "not1", name: "id", type: "UUID", nullable: false, isPrimaryKey: true, isUnique: true, autoGenerated: true, defaultValue: "gen_random_uuid()", description: "Notification record ID" },
          { id: "not2", name: "customer_id", type: "UUID", nullable: false, isPrimaryKey: false, isUnique: false, autoGenerated: false, description: "Recipient customer ID" },
          { id: "not3", name: "channel", type: "VARCHAR(20)", nullable: false, isPrimaryKey: false, isUnique: false, autoGenerated: false, description: "EMAIL, SMS, PUSH" },
          { id: "not4", name: "template", type: "VARCHAR(50)", nullable: false, isPrimaryKey: false, isUnique: false, autoGenerated: false, description: "Template key" },
          { id: "not5", name: "status", type: "VARCHAR(20)", nullable: false, isPrimaryKey: false, isUnique: false, autoGenerated: false, defaultValue: "'PENDING'", description: "SENT, FAILED, PENDING" },
          { id: "not6", name: "event_id", type: "VARCHAR(128)", nullable: false, isPrimaryKey: false, isUnique: false, autoGenerated: false, description: "Kafka source event ID for idempotency" },
          { id: "not7", name: "created_at", type: "TIMESTAMP", nullable: false, isPrimaryKey: false, isUnique: false, autoGenerated: true, defaultValue: "CURRENT_TIMESTAMP", description: "Log timestamp" },
        ],
        foreignKeys: [],
        indexes: [
          { id: "not_idx1", name: "idx_notification_event", columns: ["event_id"], isUnique: false, type: "BTREE", purpose: "Audit log lookup for event deduplication" },
        ],
      },
    ],
  },
];

const finflowSeedDatabases: ServiceDatabase[] = [
  {
    id: "account-db",
    name: "Account Service DB",
    type: "PostgreSQL",
    purpose: "Owns customer checking/savings accounts and balance holds.",
    owningServices: ["account-service"],
    whyChosen: "ACID isolation and row-level locking for zero negative balance guarantees.",
    tables: [
      {
        id: "tbl-account",
        name: "accounts",
        purpose: "Stores customer account balances and operational status.",
        primaryKey: "id",
        notes: "Strict non-negative check constraint (available_balance >= 0) enforced at DB level.",
        columns: [
          { id: "fa1", name: "id", type: "UUID", nullable: false, isPrimaryKey: true, isUnique: true, autoGenerated: true, defaultValue: "gen_random_uuid()", description: "Account ID" },
          { id: "fa2", name: "customer_id", type: "UUID", nullable: false, isPrimaryKey: false, isUnique: false, autoGenerated: false, description: "Customer owner ID" },
          { id: "fa3", name: "account_type", type: "VARCHAR(20)", nullable: false, isPrimaryKey: false, isUnique: false, autoGenerated: false, description: "CHECKING, SAVINGS" },
          { id: "fa4", name: "currency", type: "VARCHAR(3)", nullable: false, isPrimaryKey: false, isUnique: false, autoGenerated: false, description: "USD, EUR, GBP" },
          { id: "fa5", name: "ledger_balance", type: "DECIMAL(15,2)", nullable: false, isPrimaryKey: false, isUnique: false, autoGenerated: false, defaultValue: "0.00", description: "Settled book balance" },
          { id: "fa6", name: "available_balance", type: "DECIMAL(15,2)", nullable: false, isPrimaryKey: false, isUnique: false, autoGenerated: false, defaultValue: "0.00", description: "Spendable balance after holds" },
          { id: "fa7", name: "status", type: "VARCHAR(20)", nullable: false, isPrimaryKey: false, isUnique: false, autoGenerated: false, defaultValue: "'ACTIVE'", description: "ACTIVE, FROZEN, CLOSED" },
          { id: "fa8", name: "version", type: "BIGINT", nullable: false, isPrimaryKey: false, isUnique: false, autoGenerated: false, defaultValue: "0", description: "Optimistic locking version" },
        ],
        foreignKeys: [],
        indexes: [
          { id: "fa_idx1", name: "idx_account_customer", columns: ["customer_id"], isUnique: false, type: "BTREE", purpose: "Lookup customer accounts" },
        ],
      },
    ],
  },
  {
    id: "ledger-db",
    name: "Double-Entry Ledger DB",
    type: "PostgreSQL",
    purpose: "Immutable double-entry debit/credit journal entries.",
    owningServices: ["ledger-service"],
    whyChosen: "100% auditability; UPDATE and DELETE triggers disabled.",
    tables: [
      {
        id: "tbl-journal",
        name: "journal_entries",
        purpose: "Header record for balanced double-entry accounting transactions.",
        primaryKey: "id",
        notes: "Guarantees sum(debits) == sum(credits) for every entry.",
        columns: [
          { id: "fl1", name: "id", type: "UUID", nullable: false, isPrimaryKey: true, isUnique: true, autoGenerated: true, defaultValue: "gen_random_uuid()", description: "Journal Entry ID" },
          { id: "fl2", name: "transaction_ref", type: "VARCHAR(100)", nullable: false, isPrimaryKey: false, isUnique: true, autoGenerated: false, description: "External transaction reference" },
          { id: "fl3", name: "entry_type", type: "VARCHAR(30)", nullable: false, isPrimaryKey: false, isUnique: false, autoGenerated: false, description: "P2P_TRANSFER, ACH_CREDIT" },
          { id: "fl4", name: "posted_at", type: "TIMESTAMP", nullable: false, isPrimaryKey: false, isUnique: false, autoGenerated: true, defaultValue: "CURRENT_TIMESTAMP", description: "Posting timestamp" },
        ],
        foreignKeys: [],
        indexes: [
          { id: "fl_idx1", name: "idx_journal_ref", columns: ["transaction_ref"], isUnique: true, type: "BTREE", purpose: "Idempotent transaction posting" },
        ],
      },
    ],
  },
];

const logisticsSeedDatabases: ServiceDatabase[] = [
  {
    id: "fleet-db",
    name: "Fleet & Driver DB",
    type: "PostgreSQL",
    purpose: "Delivery vehicles and active driver dispatch rosters.",
    owningServices: ["fleet-service"],
    whyChosen: "ACID store for delivery fleet vehicles and driver shifts.",
    tables: [
      {
        id: "tbl-vehicle",
        name: "vehicles",
        purpose: "Delivery vans and mobile IoT telemetry IDs.",
        primaryKey: "id",
        notes: "Telemetry IoT device ID mapped to vehicle record.",
        columns: [
          { id: "lv1", name: "id", type: "UUID", nullable: false, isPrimaryKey: true, isUnique: true, autoGenerated: true, defaultValue: "gen_random_uuid()", description: "Vehicle ID" },
          { id: "lv2", name: "vin", type: "VARCHAR(50)", nullable: false, isPrimaryKey: false, isUnique: true, autoGenerated: false, description: "Vehicle VIN" },
          { id: "lv3", name: "device_id", type: "VARCHAR(100)", nullable: false, isPrimaryKey: false, isUnique: true, autoGenerated: false, description: "IoT Telemetry Hardware ID" },
          { id: "lv4", name: "status", type: "VARCHAR(20)", nullable: false, isPrimaryKey: false, isUnique: false, autoGenerated: false, defaultValue: "'AVAILABLE'", description: "AVAILABLE, IN_TRANSIT, MAINTENANCE" },
        ],
        foreignKeys: [],
        indexes: [
          { id: "lv_idx1", name: "idx_vehicle_device", columns: ["device_id"], isUnique: true, type: "BTREE", purpose: "IoT telemetry ping routing" },
        ],
      },
    ],
  },
  {
    id: "routing-db",
    name: "Spatial Routing & PostGIS DB",
    type: "PostgreSQL + PostGIS",
    purpose: "Geospatial stop sequences, bounding box queries, and parcel routes.",
    owningServices: ["routing-service"],
    whyChosen: "PostGIS extension enables R-Tree spatial indexing and fast distance calculations.",
    tables: [
      {
        id: "tbl-route-stops",
        name: "route_stops",
        purpose: "Sequenced delivery stops with spatial coordinates.",
        primaryKey: "id",
        notes: "PostGIS ST_DWithin and ST_Distance queries for dynamic re-routing.",
        columns: [
          { id: "lr1", name: "id", type: "UUID", nullable: false, isPrimaryKey: true, isUnique: true, autoGenerated: true, defaultValue: "gen_random_uuid()", description: "Stop ID" },
          { id: "lr2", name: "route_id", type: "UUID", nullable: false, isPrimaryKey: false, isUnique: false, autoGenerated: false, description: "Parent Route ID" },
          { id: "lr3", name: "stop_sequence", type: "INTEGER", nullable: false, isPrimaryKey: false, isUnique: false, autoGenerated: false, description: "Sequence order" },
          { id: "lr4", name: "parcel_id", type: "UUID", nullable: false, isPrimaryKey: false, isUnique: false, autoGenerated: false, description: "Parcel ID" },
          { id: "lr5", name: "latitude", type: "DOUBLE PRECISION", nullable: false, isPrimaryKey: false, isUnique: false, autoGenerated: false, description: "WGS84 Latitude" },
          { id: "lr6", name: "longitude", type: "DOUBLE PRECISION", nullable: false, isPrimaryKey: false, isUnique: false, autoGenerated: false, description: "WGS84 Longitude" },
          { id: "lr7", name: "status", type: "VARCHAR(20)", nullable: false, isPrimaryKey: false, isUnique: false, autoGenerated: false, defaultValue: "'PENDING'", description: "PENDING, DELIVERED, FAILED" },
        ],
        foreignKeys: [],
        indexes: [
          { id: "lr_idx1", name: "idx_route_sequence", columns: ["route_id", "stop_sequence"], isUnique: true, type: "BTREE", purpose: "Ordered stop retrieval" },
        ],
      },
    ],
  },
];
